### ISSUE TITLE
Feature: Class path filtering

### ISSUE THREAD

**Issue by clemi2408** [victools/jsonschema-generator#104]
Hi Victools-Team, 

as i saw that Feature in the gravitee plugin, i would love to have a filter functionality based on GLOB syntax to include and exclude classes:
https://github.com/gravitee-io/json-schema-generator-maven-plugin

Example:
> Generate all classes ending by ``Schema`` would be written as:
> ```xml
> <include>*Schema.class</include>
> ```

**Comment by CarstenWickner** [comment]
Hi @clemi2408,

I've created PR #132 to address this feature request.
The proposed solution adds support for glob like patterns in the existing `<classNames>` and `<packageNames>` elements and introduces a new `<excludeClassNames>` element counter-part.

Your particular example would be possible, but would look slightly differently:
> Generate all classes ending by Schema would be written as:
> ```xml
> <classNames>**Schema</classNames>
> ```

**Comment by CarstenWickner** [comment]
This has been included in the [v4.14.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.14.0) release.
