### ISSUE TITLE
Support for @JsonIdentityReference and @JsonIdentityInfo

### ISSUE THREAD

**Issue by JanLabrie** [victools/jsonschema-generator#112]
When a member of a Java class is annotated with @JsonIdentityReference, Jackson will serialize it as a reference to another object, instead of the full nested object. The reference is derived from the @JsonIdentifyInfo annotation on the referenced class.

Examples and Javadoc is found [here](https://www.logicbig.com/tutorials/misc/jackson/json-identity-reference.html) and [here](https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonIdentityReference.html)

The current schema generator does not take that into account. 

I would be good when the generator will recognize the @JsonIdentifyReference in the Jackson module and generate the type information of the id of the references object instead of the object itself.

In my project I made an implementation of this. I will prepare a PR for it, so you can form an opinion.

**Comment by CarstenWickner** [comment]
Hi @JanLabrie,

I guess you didn't get around to providing that PR.
I'll introduce the basic version myself now in #298.

I'd still appreciate it if you happened to have some feedback on my solution. 😉
