### ISSUE TITLE
Property with @JsonIgnore is excluded even though there is a getter with @JsonProperty

### ISSUE THREAD

**Issue by jochenberger** [victools/jsonschema-generator#114]
I have a bean class that looks like this:
```java
public class TestDto {

    @JsonIgnore
    private String name;

    @JsonProperty("name")
    public String getTheName() {
        return name;
    }
}
```
The generated schema does not include the `name` property. It gets filtered out by  `JacksonModule.shouldIgnoreField(FieldScope)` where it says

```java
        // other kinds of field ignorals are handled implicitly, i.e. are only available by way of being absent
        return beanDescription.findProperties().stream()
                .noneMatch(propertyDefinition -> fieldName.equals(propertyDefinition.getInternalName()));
```
Should we really use `getInternalName()` there instead of `getName()`?

**Comment by CarstenWickner** [comment]
HI @jochenberger,

First off, there seem to be some different understandings here:
 1. A method called `getTheName()` could be a getter for a field called `theName`.
 2. When there is a `@JsonIgnore` annotation, why shouldn't it be ignored? Regardless of any additional annotations.
 3. In your particular example, the `getName()` coincidentally returns the value you're looking for but `getInternalName()` is the right choice here for situations like this (where `getInternalName()` returns the `"nameInJava"` with which to compare the technical `fieldName` in your given snippet):
```java
class TestDto {
    @JsonProperty("name_in_json")
    private String nameInJava;
}
```

What you're after is a feature that is currently not supported out-of-the-box but is possible to achieve via configuration: to derive properties based on encountered methods and their `@JsonProperty` annotations and not based on the internal fields.

**Comment by CarstenWickner** [comment]
To add to the above: The given snippet from `JacksonModule.shouldIgnoreField(FieldScope)` is focusing on fields.

In order to consider the `getTheName()` method, the `JacksonModule` would have to be extended to also apply to the `configBuilder.forMethods()` part. Via `.withPropertyNameOverrideResolver()` you'd have to replace the internal name (`"getTheName()"`) with the `"name"` value from the `@JsonProperty` annotation.
However, this is only necessary in cases where the method is not a getter (according to general naming conventions) for an existing field. Is that what you have in your "real" use case?

**Comment by jochenberger** [comment]
Thanks for the helpful comments.
Yes, actually, my method is not a getter in the strict sense. My field is a `Set` and my getter takes a `Map`, because that's how the data is represented externally. So not only does the method have a different name, it also has a different type, so that's something I need to take care of as well.
It may be easier to modify the generated JSON on a node level. :-/

**Comment by CarstenWickner** [comment]
There is also a configuration option for changing a property's type. That'd be `.withTargetTypeOverridesResolver()` – you shouldn't have use custom definitions for that, but you can of course go that way too.

**Comment by jochenberger** [comment]
I wonder if I'm doing something wrong or if it's a valid use-case that is just not (yet) supported by the Jackson module.

**Comment by CarstenWickner** [comment]
I wouldn’t say your doing anything. It’s more like a not so common use case that is just not supported in this library yet.

But I’m sure we can come up with something. If the jackson itself is supporting it, it’s valid and should be supported here in one way or another.
We’ll just have to see whether it makes sense to incorporate in the `JacksonModule` directly or whether it’ll just be a combination of configurations to make it work somehow.

**Comment by jochenberger** [comment]
Sounds reasonable.
So, I think we'll have to consider the name and type changing issues separately, right?

**Comment by CarstenWickner** [comment]
I'd say if the method already declared the correct return type, you'd only need a `PropertyNameOverride` and include `configBuilder.with(Option.NONSTATIC_NONVOID_NONGETTER_METHODS)` to have them be included (which is not the case in the `OptionPreset.PLAIN_JSON` by default).
So maybe something like:
```java
SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON);
configBuilder
        .with(Option.NONSTATIC_NONVOID_NONGETTER_METHODS)
        .with(new JacksonModule());
configBuilder.forMethods()
        .withIgnoreCheck(method -> method.getAnnotation(JsonProperty.class) == null)
        .withPropertyNameOverrideResolver(method -> method.getAnnotation(JsonProperty.class).value());
```

**Comment by jochenberger** [comment]
almost, but now the key is "name()" because it's a method.

**Comment by CarstenWickner** [comment]
Alright, then we have a problem. 😃
Probably makes sense to allow the parentheses to be skipped somehow so a method can be treated as a field – I'll look into that separately.

For now, you could use a `TypeAttributeOverride` and simply change the name (or just discard the parentheses wherever there are any) in the produced `properties` in the JSON Schema.

When I find the time later, I may provide you a more specific example.

**Comment by jochenberger** [comment]
So, you mean something like this? 
```java
            // workaround for
            // https://github.com/victools/jsonschema-generator/issues/114
            configBuilder.with(Option.NONSTATIC_NONVOID_NONGETTER_METHODS).with(jacksonModule);
            configBuilder.forMethods()
                    .withIgnoreCheck(method -> method.getAnnotation(JsonProperty.class) == null)
                    .withPropertyNameOverrideResolver(
                            method -> method.getAnnotation(JsonProperty.class).value());
            configBuilder.forTypesInGeneral()
                    .withTypeAttributeOverride((collectedTypeAttributes, scope, context) -> Optional
                            .ofNullable(collectedTypeAttributes.get("properties"))
                            .map(ObjectNode.class::cast).ifPresent(properties -> {
                                List<String> keysToReplace = StreamSupport
                                        .stream(Spliterators.spliteratorUnknownSize(
                                                properties.fieldNames(), Spliterator.ORDERED),
                                                false)
                                        .filter(key1 -> key1.endsWith("()"))
                                        .collect(Collectors.toList());
                                keysToReplace.forEach(key2 -> {
                                    String newKey = key2.substring(0, key2.length() - 2);
                                    JsonNode value = properties.remove(key2);
                                    properties.set(newKey, value);
                                });
                            }));
            //
```
Phew. ;-)

**Comment by CarstenWickner** [comment]
Correct, something like that. There is still some potential to clean it up a bit, but yes.

**Comment by CarstenWickner** [comment]
There is a new `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS` (coming in release 4.13.0) to get rid of the extraneous parentheses.

So the following should do the trick then:
```java
SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON);
configBuilder
        .with(Option.NONSTATIC_NONVOID_NONGETTER_METHODS, Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS)
        .with(new JacksonModule());
configBuilder.forMethods()
        .withIgnoreCheck(method -> method.getAnnotation(JsonProperty.class) == null)
        .withPropertyNameOverrideResolver(method -> method.getAnnotation(JsonProperty.class).value());
```
