### ISSUE TITLE
How to access "parent's" field that holds the reference to the current field

### ISSUE THREAD

**Issue by jochenberger** [victools/jsonschema-generator#115]
Sorry, I have to ask another question. That's what you get for being so helpful. ;-)
I'm trying to write a module that consumes Swagger v3 annotations.
I have the following class structure (more or less)
```java
interface IReference {
  String getName();
}

class Reference<T> extends IReference {

}
@Schema(description= "the foo's person")
interface PersonReference extends IReference {
  @Schema(description = "the person's name")
  String getName();
}

class Foo {
  @Schema(implementation = PersonReference.class)
  private Reference<Person> person;
}
```
In my module, I want to resolve the description for `Foo.person.name`, but in the description resolver, I only get a reference to the `name` field in the `Reference` class. I somehow need to resolve the `@Schema#implementation()` from there but I can't seem to access the `Foo.person` field from there.
```java
class MyModule {
  .... 
  fieldConfigPart.withDescriptionResolver(member -> {
    // member is the "name" field in Reference which does not have a @Schema annotation
    // how can I access the "name" field from PersonReference here?
    // I can only move up to Reference<Person> via member.getDeclaringType
  }
}
```
Does that make sense?

**Comment by CarstenWickner** [comment]
Hi @jochenberger,

Sounds like you want something like this:
```java
configBuilder.forFields()
        .withTargetTypeOverridesResolver(field -> {
            Schema annotation = field.getAnnotation(Schema.class);
            if (annotation == null || annotation.schema() == Void.class) {
                return null;
            }
            return Collections.singletonList(field.getContext().resolve(annotation.schema()));
        });
```

This should cause the field to be treated as the right type (i.e. `PersonReference` here).

**Comment by jochenberger** [comment]
Oh, I guess I should have checked whether there are any WiP branches already. I guess I'll dump my custom implementation and take yours instead. Can I somehow help getting that ready to be included?
One thing I noticed is that the methods in `PersonReference` are apparently not being picked up as fields. I need to enable `GETTER_METHODS` for them to be included. Which again requires me to rewrite property names.
Also, your Swagger2Module does not pick up the description from `@Schema` annotations in classes referenced via `implementation` (`"the foo's person"`) in my example.

**Comment by CarstenWickner** [comment]
I'd appreciate any help on this. So maybe checkout/clone the repository including that branch and continue extending its functionality. I'd love to receive a Pull Request from you.

Fully agree, that it's not near to completion yet – unfortunately I haven't had much time lately, that's why my progress on it is rather slow. And there are some challenges with the more complex parts of the `@Schema` annotation, but I guess those could be tackled in subsequent versions.

If you have the capacity for it, please add everything you need to make your use case work to the pending branch and create a PR. Based on that, I could create the first release that you would be able to use then, while further aspects could be added later on.

**Comment by jochenberger** [comment]
> The whole "fields from methods" naming topic, should probably be a separate Issue then as it's a far smaller scope.

I'll leave that up to you since you already seem to have a solution in mind and I'd properly create an issue that's completely missing the point. :-D

**Comment by CarstenWickner** [comment]
GH-119 is introducing a new `Option` to allow using methods as the leading sources for properties.

**Comment by CarstenWickner** [comment]
Hi @jochenberger,

Again, thank you so much for helping with the new `Swagger2Module` and pushing me to finally get its first version out.

Besides this new module, release [v4.13.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.13.0) also introduces the aforementioned `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS`.

Please let me know whether your use-case is now covered and this issue can be closed.

**Comment by jochenberger** [comment]
Yes, it all works fine with a few configuration options set. Thank you so much for your help.
