### ISSUE TITLE
How to add condition in JSON Schema

### ISSUE THREAD

**Issue by pahujatarun25** [victools/jsonschema-generator#121]
Hi,

First of all. thank you for providing great api to work with for JSON Schema.
I am actually to trying to define condition in JSON Schema. 
Lets say if have a following class:
```java
class Student {
    private DressColor dressColor; //DressColor is ENUM
    private int fineApplicable;
}
```

I want my json schema to have following condition:
- If `dressColor` is `"GREY"`, `fineApplicable` field should be `required`.

There are similar examples on stackoverflow as well:
https://stackoverflow.com/questions/38717933/jsonschema-attribute-conditionally-required

Could you please how we can add these conditions in JSON schema using the library. 

Thanks,
Tarun

**Comment by CarstenWickner** [comment]
Hi Tarun,

By design, there are multiple ways to describe constraints such as your example in a JSON Schema. I presume you're aware, since the linked StackOverflow question's top answer already outlines four alternative approaches -- all of which are technically possible to achieve via the `jsonschema-generator` here.

Do you have a preference, what the resulting JSON Schema should look like?
Then I could give you more specific steps for how to achieve it. Currently, (almost) all of your options require a certain degree of "customisation", i.e. you have to create nodes in the generated schema yourself.

**Comment by pahujatarun25** [comment]
Hi,
Thanks for your answer. I would like to generate schema in the following manner:
{
  "type": "object",
  "properties": {
    "dressColor": { "enum": ["GREY", "WHITE"] },
    "fineApplicable": { "type": "int" }
  },
  "anyOf": [
    {
      "properties": {
        "dressColor": { "const": "GREY" }
      },
      "required": ["fineApplicable"]
    }
  ]
}
Could you please post sample code to generate such a schema.
Thanks.

**Comment by pahujatarun25** [comment]
Hi,
Thanks for your answer. I would like to generate schema in the following manner:
```
{
"type": "object",
"properties": {
"dressColor": { "enum": ["GREY", "WHITE"] },
"fineApplicable": { "type": "int" }
},
"anyOf": [
{
"properties": {
"dressColor": { "const": "GREY" }
},
"required": ["fineApplicable"]
}
]
}
```
Could you please post sample code to generate such a schema.
Thanks.

**Comment by CarstenWickner** [comment]
Hi Tarun,

There are two points in your target schema that need correction:
- There is no `"type": "int"`, but `"type": "integer"` is what you want.
- The `anyOf` needs to have an alternative in it. Either expecting the `"dressColor"` to be `"WHITE"` or at least `not` `"GREY"`.

With the following snippet:
```java
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfig;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaKeyword;
import com.github.victools.jsonschema.generator.SchemaVersion;

public class ConditionAnyOfExample {

    public static void main(String[] args) {
        SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON);
        configBuilder.forTypesInGeneral()
                .withTypeAttributeOverride((schemaNode, scope, context) -> {
                    if (scope.getType().getErasedType() == Student.class) {
                        ObjectNode greyDressCondition = context.getGeneratorConfig().createObjectNode();
                        greyDressCondition.with(context.getKeyword(SchemaKeyword.TAG_PROPERTIES))
                                .with("dressColor")
                                .put(context.getKeyword(SchemaKeyword.TAG_CONST), DressColor.GREY.name());
                        greyDressCondition.withArray(context.getKeyword(SchemaKeyword.TAG_REQUIRED))
                                .add("fineApplicable");
                        ObjectNode whiteDressCondition = context.getGeneratorConfig().createObjectNode();
                        whiteDressCondition.with(context.getKeyword(SchemaKeyword.TAG_PROPERTIES))
                                .with("dressColor")
                                .put(context.getKeyword(SchemaKeyword.TAG_CONST), DressColor.WHITE.name());
                        schemaNode.withArray(context.getKeyword(SchemaKeyword.TAG_ANYOF))
                                .add(greyDressCondition)
                                .add(whiteDressCondition);
                    }
                });
        SchemaGeneratorConfig config = configBuilder.build();
        SchemaGenerator generator = new SchemaGenerator(config);
        JsonNode jsonSchema = generator.generateSchema(Student.class);

        System.out.println(jsonSchema.toPrettyString());
    }

    enum DressColor {
        GREY, WHITE;
    }

    class Student {

        DressColor dressColor;
        int fineApplicable;
    }
}
```

You can produce this schema:
```json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "type" : "object",
  "properties" : {
    "dressColor" : {
      "type" : "string",
      "enum" : [ "GREY", "WHITE" ]
    },
    "fineApplicable" : {
      "type" : "integer"
    }
  },
  "anyOf" : [ {
    "properties" : {
      "dressColor" : {
        "const" : "GREY"
      }
    },
    "required" : [ "fineApplicable" ]
  }, {
    "properties" : {
      "dressColor" : {
        "const" : "WHITE"
      }
    }
  } ]
}
```

**Comment by pahujatarun25** [comment]
Hi,
Thanks again for wonderful response. I have one query:
I have actually defined properties name using JsonProperties as:
```
    class Student {
        @JsonProperty("uniformColor")
        DressColor dressColor;
       @JsonProperty("fine")
        int fineApplicable;
    }
```
And overriding them as:
```
               configBuilder.forFields().withPropertyNameOverrideResolver(field -> {
			 JsonProperty annotation = field.getAnnotationConsideringFieldAndGetter(JsonProperty.class);
			 return annotation == null || annotation.value().isEmpty()?null: annotation.value();
		});
```

Is it possible to get rid of hardcoding of "dressColor" in your above texted code snipped and somehow use property name defined by JsonProperty ?

Thanks,
Tarun

**Comment by pahujatarun25** [comment]
As a solution, I am using reflection to obtain named defined by JsonProperty. 
Student.class.getField("dressColor").getAnnotation(JsonProperty.class).value();

**Comment by CarstenWickner** [comment]
Hi Tarun,

If you use the `jsonschema-module-jackson`, you wouldn’t have to change the field names yourself.

As per your workaround, something needs to be hard-coded for this conditional construct unless you have dedicated subtypes (which would be supported through the `@JsonSubTypes` and `@JsonTypeInfo` annotations).

Whether you hard-code the name in the code or in the JSON is up to your personal preference I guess.

**Comment by pahujatarun25** [comment]
Thanks for much help.
