### ISSUE TITLE
Configuring schema with exclusive maxima/minima producing incorrect schema

### ISSUE THREAD

**Issue by pahujatarun25** [victools/jsonschema-generator#122]
Hi,

I am configuring schema as follow to use exclusive maximum:
```
configBuilder.forFields().withNumberExclusiveMaximumResolver(field ->
 {
           Max annotation = field.getAnnotationConsideringFieldAndGetter(Max.class);
          return annotation != null ? new BigDecimal(annotation.value()) : null;
});
```

However I am getting  ("exclusiveMaximum":1E+1) in my schema instead of actual value (which is 10). The annotation MAX returning long type value. I also tried with hardcoded value "10l" but got same result.

Could you please help. 

Thanks,
Tarun

**Comment by CarstenWickner** [comment]
Hi Tarun,

You might want to look into the `jsonschema-module-javax` to get support for annotations like `@Max` out-of-the-box.

As to the scientific notation for numbers, that is a setting on the jackson `ObjectMapper`, i.e. you’ll have to disable the scientific notation on the `ObjectMapper` directly.

**Comment by pahujatarun25** [comment]
As suggested, I started using` jsonschema-module-javax-validation` . However now I am getting strange error. If I specify value "15" in Max notation, value comin as plain text. But If I give "10", "100", "1000" etc, value appearing in scientific notation in the schema.
I have also tried disabling mapper as follow:

```
ObjectMapper mapper = new ObjectMapper();
mapper.configure(JsonGenerator.Feature.WRITE_NUMBERS_AS_STRINGS, true);
SchemaGeneratorConfigBuilder configBuilder = 
				new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON).with(module); 
```

The problem seems to appearing in cases where I specify values in multiple of 10.

**Comment by CarstenWickner** [comment]
In the given snippet, your not including the `ObjectMapper` in the config builder’s constructor, i.e. it is not being considered.

**Comment by CarstenWickner** [comment]
You might need special handling for `BigDecimal` as that’s what is being used internally. The parameter you enabled may not apply to those.

**Comment by pahujatarun25** [comment]
Hi,
I tried but it does not seem to be working even with that option:
```
		mapper.configure(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN, true);
		SchemaGeneratorConfigBuilder configBuilder = 
				new SchemaGeneratorConfigBuilder(mapper,SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON).
				with(module);
```

**Comment by CarstenWickner** [comment]
It seems like the `Feature` is not properly forwarded to the default pretty printer when it was defined via `ObjectMapper.configure()`.

This does the trick for me:
```java
JsonNode jsonSchema = generator.generateSchema(Student.class);
System.out.println(mapper.writerWithDefaultPrettyPrinter()
        .with(Feature.WRITE_BIGDECIMAL_AS_PLAIN)
        .writeValueAsString(jsonSchema));
```

**Comment by pahujatarun25** [comment]
Thanks its working fine now.
