### ISSUE TITLE
How to create json schema consisting of inclusive forbidden fields ?

### ISSUE THREAD

**Issue by pahujatarun25** [victools/jsonschema-generator#124]
Hi,

I am not sure how to generate schema for the following condition. Could you please help.
I have following class:
```
Class Job{
   private CASTE caste;
   private String reservationPercent;
   private String ageRelaxation;
}
```

Where the ENUM case is defined as
```
enum CASTE{
OBC,
GENERAL,
SC_ST;
}
```
I want to convey in my schema that "reservationPercent" and "ageRelaxtion" field should not be in the schema (inclusive forbidden) if CASTE is GENERAL. 
I dont know even if its possible via anyOf or oneOf.

Could you please help, if you have idea about it.

**Comment by CarstenWickner** [comment]
If it's about the target schema, this should do:
```json
{
   "type": "object",
   "properties": {
      "caste": { "enum": ["OBC", "GENERAL", "SC_ST"] },
      "reservationPercent": { "type": "string" },
      "ageRelaxation": { "type": "string" }
   },
   "required": ["caste"],
   "anyOf": [
      {
         "properties": {
            "caste": { "enum": ["OBC", "SC_ST"] }
         },
         "required": ["reservationPercent", "ageRelaxation"]
      },
      {
         "properties": {
            "caste": { "const": ["GENERAL"] }
         },
         "allOf": [
            { "not": { "required": ["reservationPercent"] } },
            { "not": { "required": ["ageRelaxation"] } }
         ]
      }
   ]
}
```

**Comment by pahujatarun25** [comment]
Thanks,
I thought, not required means, optional which means validator wont give error even if those fields are available. I will test. 
Thanks a lot.

**Comment by pahujatarun25** [comment]
I think the following would equally work fine without allOf:
```
"anyOf": [
      {
         "properties": {
            "caste": { "enum": ["OBC", "SC_ST"] }
         },
         "required": ["reservationPercent", "ageRelaxation"]
      },
      {
         "properties": {
            "caste": { "const": ["GENERAL"] }
         },
         "not": {
           "required": ["reservationPercent", "ageRelaxation"]
         }
      }
   ]
```

**Comment by pahujatarun25** [comment]
I think, You are not supporting "not" keyword in SchemaKeyword. 
If you allow, I would like to contribute to this project too.

**Comment by CarstenWickner** [comment]
Hi @pahujatarun25,

Unfortunately, `"not": { "required": ["reservationPercent", "ageRelaxation"] }` will still allow one of the two fields being present. It will only fail if both are present.

You can just use the string `"not"` directly. No need to add it to the `SchemaKeyword` enum at this stage, as there is no special handling for it and there is no nice way of deriving this from code.

**Comment by pahujatarun25** [comment]
From client perspective, it does not look good to mix Constants with hardcoded strings. For client, anyway library is a abstract concept and it does not really matter what it does internally as long as required functionality is met.
Thanks for providing wonderful library to handle json schema.

**Comment by CarstenWickner** [comment]
Hi @pahujatarun25,

I can appreciate that you want to avoid hard-coding these things. On the other hand, once these keywords are added to the `SchemaKeyword` enum I feel obligated to maintain them in the future and I dread a situation like the split-up of `"dependencies"` into `"dependencies"` and `"dependentSchemas"` where there is no clean-cut one-to-one relationship between keywords in different JSON Schema Drafts anymore.

That being said, I had already hard-coded `"not"`/`"minProperties"`/`"maxProperties"` in the recently added `jsonschema-module-swagger-2`, i.e. I will have to maintain those now anyway. Therefore, those three entries will be added in the next release `v4.14.0` to the `SchemaKeyword`.
