### ISSUE TITLE
Support for ordering of properties

### ISSUE THREAD

**Issue by pahujatarun25** [victools/jsonschema-generator#125]
Hi,

What I have noticed so far that generated schema list properties in alphabetical order. Is it possible to tell schema generator to list properties in the same order it is listed in the source code ? 

Thanks for your support.

**Comment by CarstenWickner** [comment]
Hi @pahujatarun25,

You can use the `configBuilder.forTypesInGeneral().withPropertySorter()`.

If the configured `Comparator` always returns 0, the order in which they are encountered will be preserved. However, depending on the compiling JVM this may or may not reflect the order in the source code.

To be sure of the order, you’d have to base it on something else, e.g. adding `@JsonPropertyOrder` annotations everywhere.

This was already discussed at length on the original issue/PR (I‘ll add the reference later).

**Comment by pahujatarun25** [comment]
Thank you for your response. However order is being preserved among object definitions:
For e.g. if I have a following class:

```
Class OneLevelTree{
private String name;
private String description;
private Node root;
}

Class Node {
private LeftNode leftChild;
private RightNode rigtChild;
private MiddleNode middleChild;
}

class LeftNode  {

}

class RightNode {

}

class MiddleNode {
}
```

It produces following JSON Schema:
```
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "description" : {
      "type" : "string"
    },
    "root" : {
      "$ref" : "#/definitions/Node"
    }
  },
  "additionalProperties" : false,
  "definitions" : {
    "LeftNode" : {
      "type" : "object",
      "additionalProperties" : false
    },
    "MiddleNode" : {
      "type" : "object",
      "additionalProperties" : false
    },
    "Node" : {
      "type" : "object",
      "properties" : {
        "leftChild" : {
          "$ref" : "#/definitions/LeftNode"
        },
        "rigtChild" : {
          "$ref" : "#/definitions/RightNode"
        },
        "middleChild" : {
          "$ref" : "#/definitions/MiddleNode"
        }
      },
      "additionalProperties" : false
    },
    "RightNode" : {
      "type" : "object",
      "additionalProperties" : false
    }
  }
}
```
As you can see, order is not maintained in the definition section.

**Comment by CarstenWickner** [comment]
Hi @pahujatarun25,

The `definitions` keyword is a different topic as it's not representing a single object's properties but a dictionary from which to look-up re-used subschemas. This may contain dozens/hundreds/thousands of subschemas depending on the main schema's complexity. The order in which those subschemas are encountered is (a) not guaranteed in any way, (b) quickly becomes meaningless when encountered more than once and (c) hardly human-readable if it's effectively in a random order.

Therefore, the `definitions` are sorted alphabetically.

----

That being said, I'm curious what specific use-case you have for a particular order of the `definitions`.
I'd be interested to read the reason for and description of any other sorting that you'd deem meaningful here.
