### ISSUE TITLE
Schema Generation with Custom Serialization

### ISSUE THREAD

**Issue by jbaker-dstl** [victools/jsonschema-generator#127]
I have Jackson configured to use a custom serializer for the java.util.regex.Pattern, which serializes instances of Pattern as a String rather than as an object.

I pass a configured ObjectMapper into the JSON Schema Generator via the SchemaGeneratorConfigBuilder, but if I then request a the Schema for an object that uses Pattern, rather than getting a `string` type I get an `object` as if I wasn't using the custom serializer.

Is it possible to configure JSON Schema Generator to respect custom serialization?

**Comment by CarstenWickner** [comment]
Hi James,

Since your mapping is straightforward, it shouldn't be too much trouble of applying an equivalent configuration on the Schema Generator such as the following one (beware that support for `"format": "regex"` was only added in Draft 7):
```java
configBuilder.forTypesInGeneral().withCustomDefinitionProvider((type, context) -> {
    if (type.getErasedType() != Pattern.class) {
        return null;
    }
    ObjectNode customPatternSchema = context.getGeneratorConfig().createObjectNode()
            .put(context.getKeyword(SchemaKeyword.TAG_TYPE), context.getKeyword(SchemaKeyword.TAG_TYPE_STRING))
            .put(context.getKeyword(SchemaKeyword.TAG_FORMAT), "regex");
    return new CustomDefinition(customPatternSchema, true);
});
```

As to the possibility of picking it up automatically: the scope is a bit different unfortunately. A custom serializer handles a particular object instance and may treat it differently depending on any kind of criteria. The JSON Schema is generated based on static type information, Therefore it'd be very hard (if not impossible) to automatically detect custom mappings performed by such a serializer. Or how exactly do you configure this custom serialisation?

**Comment by jbaker-dstl** [comment]
Thanks @CarstenWickner - unfortunately, the Pattern example is likely to be one of a number of custom serializations that are required so the manual approach would be quite cumbersome to manage. I am writing custom serializers/deserializers for Jackson though, so perhaps a similar concept of a "schema serializer" for this would work as that would at least keep the code separate and easier to manage. Perhaps something along the lines of:

```
configBuilder.withTypeSerializer(Pattern.class, new MyPatternSerializer())
```

I configure the serialization at the moment by configuring the ObjectMapper with additional serializers and deserializers for the types that need changing, along the lines of: https://www.baeldung.com/jackson-custom-serialization

**Comment by CarstenWickner** [comment]
Hi James,

Again, the serialisation is a different scope than the schema generation. That being said, I can appreciate that you want to group the custom schema definitions in a similar way. For that, you could create a single `CustomDefinitionProviderV2` implementation in which you include the equivalent of all of your custom serialisers.

Just as an additional note: if the mapping is as simple as the `Pattern` example, you could also simple use another existing configuration instead:
```java
configBuilder.forFields().withTargetTypeOverridesResolver(
        field -> field.getType().getErasedType() == Pattern.class
        ? Collections.singletonList(field.getContext().resolve(String.class))
        : null);
```
Again, you can make this cleaner if you have a bunch of these through something like this:
```java
private ConfigFunction<FieldScope, List<ResolvedType>> createTargetTypeOverride(Class<?> declaredType, Class<?> alternativeType) {
    return field -> field.getType().getErasedType() == declaredTypes
            ? Collections.singletonList(field.getContext().resolve(alternativeType))
            : null;
}
```
```java
configBuilder.forFields()
        .withTargetTypeOverridesResolver(this.createTargetTypeOverride(Pattern.class, String.class))
        .withTargetTypeOverridesResolver(this.createTargetTypeOverride(OtherType.class, CustomReplacementType.class));
```

**Comment by jbaker-dstl** [comment]
Thanks, I think the ability to take into account the serialization would still be useful (perhaps looking at JsonbAdapter from the JsonB spec), but the target types resolver works for now.

**Comment by CarstenWickner** [comment]
I'm open to PR (or just a snippet) how that can be accomplished – reconciling the instance scope of custom serializers and the static type scope of the schema generation.
Till then, I'll close this here as I don't know what can be done about that.
