### ISSUE TITLE
Multiple child classes of a field when generating schema

### ISSUE THREAD

**Issue by s33p** [victools/jsonschema-generator#134]
Hello, Thanks for this project.

I have a class 

```
class OnboardPet {
  Person owner;
  Animal pet;
}
```

There are many classes extending Animal
```
class Dog extends Animal {
    String specificDogProperty;
}
```

```
class Cat extends Animal {
     String someCatProperty;
}
```

So my question is, when i generate schema for class **OnboardPet**, how to include the schema for all the sub classes - Dog and Cat for the field "**pet**" in oneOf clause? something like pet: oneOf(CatSchemaDef, DogSchemaDef), etc

Also I am looking to generate this in one file itself if possible.

**Comment by s33p** [comment]
I looked in to the source and found this .withSubTypeResolver(). I Think this will help. Thank you

**Comment by CarstenWickner** [comment]
Yes, the `SubtypeResolver` should give you want you want.
Maybe checkout the Wiki for some extra information: https://github.com/victools/jsonschema-generator/wiki#144-subtype-resolver

Also note that the JacksonModule supports common subtype lookup methods utilising the `@JsonSubTypes` and `@JsonTypeInfo` annotations our of the box.
