### ISSUE TITLE
Support Optional as a container in validation module

### ISSUE THREAD

**Issue by ldaley** [victools/jsonschema-generator#138]
As far as I can tell, Optional and the validation module don't play well together. The pattern for validated optionals is given here:

https://docs.jboss.org/hibernate/validator/5.2/reference/en-US/html/ch02.html#_with_literal_java_util_optional_literal

So effectively,

```
Optional<@Size(min = 10) String> someString
```

Should be interpreted as:

```
@Size(min = 10)
@Nullable
String someString
```

**Comment by ldaley** [comment]
I'm going to need to do this on a current project and will likely start by forking the existing validation module. If I work it out, I'll post what I come up with back here.

**Comment by CarstenWickner** [comment]
@ldaley you might want to look into this issue then:
https://github.com/FasterXML/java-classmate/issues/25

That's why those inline annotations are currently not available.

For your particular use-case, this should already have the desired effect (just as a workaround):
```java
@Size(min = 10)
Optional<String> someString;
```

**Comment by CarstenWickner** [comment]
Hi Luke,

I'm happy to let you know, that these kinds of validation annotations are now also supported on `Optional`.
Similar to #60, this is limited to the top-level, which is hopefully good enough for your use-case.
- `Optional<@Size(min = 5) String>` will be picked up
- `List<Optional<@Size(min = 5) String>>` will **not** be picked up

It'll be included in the next release then.

**Comment by CarstenWickner** [comment]
Here you go: [release v4.15.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.15.0) is published.

**Comment by ldaley** [comment]
@CarstenWickner Thank you for the fast turnaround, and excellent library.
