### ISSUE TITLE
Is there options to produce {"enum":["abc"]} instead of {"const": "abc"}?

### ISSUE THREAD

**Issue by lasyard** [victools/jsonschema-generator#142]
If the enum has only one element, the generated schema will be {"const": ... }, which makes it inconvenient to render an UI form with [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form), where a "const" is used only in validation but not in rendering the field as a drop down list.

**Comment by CarstenWickner** [comment]
Since the `const` keyword was only introduced in Draft 6, you should be able to simply target `SchemaVersion` Draft 5 to avoid `const` being used.

**Comment by CarstenWickner** [comment]
The new `Option.ENUM_KEYWORD_FOR_SINGLE_VALUES` has been released now in [v4.16.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.16.0).
