### ISSUE TITLE
Add a gradle plugin

### ISSUE THREAD

**Issue by huehnerlady** [victools/jsonschema-generator#144]
Hi,

we are currently looking into generating a json schema from pojos. Your tool sounds perfect for this. Unfortunately I just saw a maven plugin, but we are using gradle.

Is there a plan to introduce a gradle plugin?

**Comment by CarstenWickner** [comment]
Happy to hear it suits your schema-generation needs in general.

As to a gradle plugin, there is no active plan to create one so far.
Even the maven plugin was created as a contribution. I'm merely maintaining it now.
I'm open to doing the same for a gradle plugin if you were to create one. So far, I've never created a gradle plugin myself – especially not as part of a maven multi-module project (as it should be, to make it easy to integrate in the standard release process).

Alternatively, you should be able to define an inline plugin in your `build.gradle` to make use of this library in your build process.

**Comment by CarstenWickner** [comment]
Hi @huehnerlady,

I've hardly any experience with gradle but cobbled together an example for trigger the schema generation from within a gradle build and published it here: https://github.com/victools/jsonschema-gradle-example

That basic example consist simply of this `build.gradle`:
```groovy
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaVersion;

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: 'com.github.victools', name: 'jsonschema-generator', version: '4.16.0'
    }
}
plugins {
    id 'java-library'
}

task generate {
    doLast {
        def configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON);
        // apply your configurations here
        def generator = new SchemaGenerator(configBuilder.build());
        // target the class for which to generate a schema
        def jsonSchema = generator.generateSchema(SchemaVersion.class);
        // handle generated schema, e.g. write it to the console or a file
        def jsonSchemaAsString = jsonSchema.toPrettyString();
        println jsonSchemaAsString
        new File(projectDir, "schema.json").text = jsonSchemaAsString
    }
}
```

Seems to me, Gradle is flexible enough that there is no real need for an official plugin, which just needs to be maintained.

Since you're already working with Gradle I hope this is sufficient to get you where you want to go.

**Comment by dthib** [comment]
Hi everyone,
Sorry I am not familiar with gradle a lot. In the example the SchemaVersion class is used. Has anyone successfully referred to a class in an android project for example ? I can't find a way to import it.
Thanks for your help

**Comment by CarstenWickner** [comment]
Hi @dthib,

At the top of the given example gradle build file are the import statements. Adding one for your own type should hopefully work.

Otherwise, you might have to ask somewhere gradle experts can be found (e.g. StackOverflow?). I'm certainly not falling into that category.

**Comment by dthib** [comment]
Hi @CarstenWickner,

Thanks for your answer. Unfortunately, I have already tried and it does not :). I will keep you informed.

Best

**Comment by CarstenWickner** [comment]
Hi @dthib,

One extra thought: the schema is generated based on your compiled code, i.e. you'll have to extend the given example to first compile your own code to make it available on the classpath for the schema generation.

**Comment by be-hase** [comment]
Thank you for providing such a useful library.
I have created a Gradle Plugin.  Please feel free to try it out if you’re interested.
https://github.com/be-hase/jsonschema-generator-tools
