### ISSUE TITLE
Implementing if/then/else

### ISSUE THREAD

**Issue by CathKilroy** [victools/jsonschema-generator#145]
Hi

We have started using this awesome tool, for dynamic schema creation 👍 

Is there any plans, for implementing if/then/else in the near future. We have some case, where it would be really handy. Now we implement the logic after form generation and validation. But it removes the abstraction between schemas and the rest of the code.

/Casper Thrane

**Comment by CarstenWickner** [comment]
HI Casper,

I'm happy to hear it's being used.

As to `if`/`then`/`else` the same question was asked in #130, where I also provided an example configuration.
As to supporting it In general:
> Due to the flexibility of the `if`/`then`/`else` structures, that can currently only be achieved through manually applying custom definitions or attribute overrides.

If you have a class example (where the conditional information is available through annotations or other means) and a hand-crafted schema showing what it is you want to achieve, I'd be happy to provide you the example configuration to derive the schema (if possible).

**Comment by CathKilroy** [comment]
Thank you for pointing me in the right direction. The example in #130, will help me, to solve my problem.

/Casper Thrane
