### ISSUE TITLE
Implementing oneOf/anyOf/allOf/not

### ISSUE THREAD

**Issue by CathKilroy** [victools/jsonschema-generator#146]
Hi

We are also missing, the possibilty to use the above. A use case would be ex. enums with readable titles like this:
`{
    "oneOf": [
        {"enum": ["foo"], "title": "Pick Foo"},
        {"enum": ["bar"], "title": "Pick Bar"},
        {"enum": ["whatever"], "title": "Don't Care"}
    ]
}`

Any plans for implementing the above. Or could you point us, in a direction, if we should implement it our selves.

Best Regards
Casper Thrane

**Comment by CarstenWickner** [comment]
Hi Casper,

Similarly to `if`/`then`/`else`, those structural keywords are hard to meaningfully support out-of-the-box as their flexibility makes any standard handling pretty minimal. Therefore, you'd have to resort to custom definitions and/or attribute overrides.

That being said, `anyOf` and `allOf` are already actively used in the schema generation. There is some extra handling for `oneOf` as well, to consolidate unnecessarily nested structures at the end of the schema generation.

----

For the given example – enums – there already a bunch of special handling options, but none allow for that exact output, as one would have to decide where the value and respective `title` are coming from.

In this case, I'd suggest to use a custom definition as for this example code:
```java
public class TitledEnumExample {

    public static void main(String[] args) throws JsonProcessingException {
        SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON);
        configBuilder.forTypesInGeneral()
                .withCustomDefinitionProvider(TitledEnumExample::provideCustomEnumDefinition);
        SchemaGenerator generator = new SchemaGenerator(configBuilder.build());
        JsonNode jsonSchema = generator.generateSchema(TestEnum.class);
        System.out.println(jsonSchema.toPrettyString());
    }

    private static CustomDefinition provideCustomEnumDefinition(ResolvedType javaType, SchemaGenerationContext context) {
        if (javaType.getErasedType() != TestEnum.class) {
            return null;
        }
        ObjectNode definition = context.getGeneratorConfig().createObjectNode();
        ArrayNode enumArray = definition.withArray(context.getKeyword(SchemaKeyword.TAG_ONEOF));
        for (TestEnum enumValue : TestEnum.values()) {
            enumArray.addObject()
                    .put(context.getKeyword(SchemaKeyword.TAG_TITLE), enumValue.title)
                    .withArray(context.getKeyword(SchemaKeyword.TAG_ENUM)).add(enumValue.value);
        }
        return new CustomDefinition(definition, CustomDefinition.DefinitionType.STANDARD, CustomDefinition.AttributeInclusion.NO);
    }

    static enum TestEnum {
        FOO("foo", "Pick Foo"),
        BAR("bar", "Pick Bar"),
        WHATEVER("whatever", "Don't Care");

        public String value;
        public String title;

        TestEnum(String value, String title) {
            this.value = value;
            this.title = title;
        }
    }
}
```
The produced schema looks like this:
```json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "oneOf" : [
    { "title" : "Pick Foo", "enum" : [ "foo" ] },
    { "title" : "Pick Bar", "enum" : [ "bar" ] },
    { "title" : "Don't Care", "enum" : [ "whatever" ] }
  ]
}
```
It would only need to be generalised then, to work for more than just this single referenced enum.

**Comment by CathKilroy** [comment]
Thank you! That is exactly, what i was looking for.

Custom definitions gives a great flexibility.

/Casper Thrane

**Comment by CathKilroy** [comment]
Hi again

When I add the code below to a enum field, I lose the type of the field. The type should still be string. How can I add the type?

/Casper Thrane

**Comment by CarstenWickner** [comment]
Hi Casper,

Just add it to the custom definition by including the following line:
```java
definition.put(context.getKeyword(SchemaKeyword.TAG_TYPE), context.getKeyword(SchemaKeyword.TAG_TYPE_STRING));
```

I've adjusted the full example above accordingly.
