### ISSUE TITLE
How to have a generated schema with an array at the root instead of an object

### ISSUE THREAD

**Issue by mattmackenzie** [victools/jsonschema-generator#147]
I have a number of objects that I want to indicate should be provided as an array. This works well, obviously, for class members, but not for the class itself. Is there a way to do this without manipulating the JSON post-generation?

**Comment by CarstenWickner** [comment]
Hi @mattmackenzie,

Do you mean the generated schema should be the array, containing a particular type?
```java
JsonNode jsonSchema = generator.generateSchema(ArrayList.class, YourClass.class);
```

**Comment by mattmackenzie** [comment]
Thanks @CarstenWickner. This worked for me. Much appreciated!
