### ISSUE TITLE
forMethods() in config builder, is not call

### ISSUE THREAD

**Issue by CathKilroy** [victools/jsonschema-generator#149]
Hi

I have a problem, with using forMethods. Non of the with's is called, when using the class below:
```java
public class IataCode implements Comparable<IataCode>, ExtendedDTO<IataCodeExtendedDTO> {
   private String parentCode = null;
        private String code;
	private LowerCaseHashMap<String> airportName;
	private LowerCaseHashMap<String> cityName;
	private String countryIsoCode;
	
	public final String getCode() {
		return code;
	}

	public final void setCode(String code) {
		this.code = code.toUpperCase();
	}	
	
	public final LowerCaseHashMap<String> getAirportName() {
		return airportName;
	}

	public final LowerCaseHashMap<String> getCityName() {
		return cityName;
	}

	public final String getParentCode() {
		return parentCode;
	}
	
	public List<IataCode> getChildCodes() {
		return Globals.iataCodesConfiguration.getChildCodes(code);
	}
	
	public final String getCountryIsoCode() {
		return countryIsoCode;
	}

	public String getAreaCode() {
		return Globals.countryIsoCodesConfiguration.getCode(countryIsoCode).getAreaCode();
	}
	
	@Override
	public int compareTo(IataCode iataCode) {
		return code.compareTo(iataCode.getCode());
	}

	@Override
	public String toString() {
		return "IataCode [parentCode=" + parentCode + ", code=" + code + ", airportName=" + airportName + ", cityName="
				+ cityName + ", countryIsoCode=" + countryIsoCode + "]";
	}

	@JsonIgnore
	@Override
	public IataCodeExtendedDTO getExtendedDTO() {
		return new IataCodeExtendedDTO(this);
	}
}
```
The method I would like to expose, is the getChildNodes method.

I have called it like this:
```java
configBuilder.forMethods()
    .withTitleResolver((scope) -> {
        // Set title
        System.out.println(scope);
        JsonSchema jsonSchema = scope.getAnnotationConsideringFieldAndGetter(JsonSchema.class);
        return jsonSchema != null && !"".equals(jsonSchema.title()) ? jsonSchema.title() : null;
    })
    .withDescriptionResolver((scope) -> {
        // Set description
        JsonSchema jsonSchema = scope.getAnnotationConsideringFieldAndGetter(JsonSchema.class);
        return jsonSchema != null && !"".equals(jsonSchema.description()) ? jsonSchema.description() : null;
    });
```

Br
Casper

**Comment by CarstenWickner** [comment]
Hi Casper,
What `Option` values are you including (either through the `OptionPreset` or explicitly)?
You can find an overview of the available `Option`s and what `OptionPreset` they are contained in, in the wiki:
- https://github.com/victools/jsonschema-generator/wiki#11-configuration-through-options

I suspect you're using the `OptionPreset.PLAIN_JSON` which _excludes_ all methods by default. You can either use a different `OptionPreset` or add the respective `Option` explicitly. For the `getChildNodes()` method, that'd be:
- `Option.NONSTATIC_NONVOID_NONGETTER_METHODS`

If you don't care about other methods, you might need to ignore them explicitly then.

**Comment by CathKilroy** [comment]
Hi

I am using PLAIN_JSON, together with these options:

             configBuilder.with(Option.MAP_VALUES_AS_ADDITIONAL_PROPERTIES
                                               , Option.FORBIDDEN_ADDITIONAL_PROPERTIES_BY_DEFAULT
                                               , Option.INLINE_ALL_SCHEMAS
                                               , Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS
                                               , Option.NONSTATIC_NONVOID_NONGETTER_METHODS)
                                        .without(Option.NONPUBLIC_NONSTATIC_FIELDS_WITHOUT_GETTERS);

I added the one you suggested, but it didn’t solve the problem.

Br
Casper

**Comment by CathKilroy** [comment]
Sorry, i didn’t test the prior options the right way. The prior options, actually gives me an error:

Option.INLINE_ALL_SCHEMAS cannot be fulfilled due to a circular reference to java.util.HashMap$TreeNode<java.lang.String, java.lang.String>

If i remove the inline option, the result will give me alot of entries from the map object:

{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "LowerCaseHashMap(String)": {
            "type": "object",
            "properties": {
                "empty": {
                    "type": "boolean"
                },
                "capacity()": {
                    "type": "integer"
                },
                "clone()": {},
                "compute(String, BiFunction<Object, Object, String>)": {
                    "type": "string"
                },
                "computeIfAbsent(String, Function<Object, String>)": {
                    "type": "string"
                },
                "computeIfPresent(String, BiFunction<Object, Object, String>)": {
                    "type": "string"
                },
                "containsKey(Object)": {
                    "type": "boolean"
                },
                "containsValue(Object)": {
                    "type": "boolean"
                },
                "entrySet()": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "key": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            },
                            "equals(Object)": {
                                "type": "boolean"
                            },
                            "hashCode()": {
                                "type": "integer"
                            },
                            "setValue(String)": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "equals(Object)": {
                    "type": "boolean"
                },
                "get(Object)": {
                    "type": "string"
                },
                "get(String)": {
                    "type": "string"
                },
                "getNode(int, Object)": {
                    "$ref": "#/definitions/Node(String,String)"
                },
                "getOrDefault(Object, String)": {
                    "type": "string"
                },
                "hashCode()": {
                    "type": "integer"
                },
                "keySet()": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "loadFactor()": {
                    "type": "number"
                },
                "merge(String, String, BiFunction<Object, Object, String>)": {
                    "type": "string"
                },
                "newNode(int, String, String, Node<String, String>)": {
                    "$ref": "#/definitions/Node(String,String)"
                },
                "newTreeNode(int, String, String, Node<String, String>)": {
                    "$ref": "#/definitions/TreeNode(String,String)"
                },
                "put(String, String)": {
                    "type": "string"
                },
                "putIfAbsent(String, String)": {
                    "type": "string"
                },
                "putVal(int, String, String, boolean, boolean)": {
                    "type": "string"
                },
                "remove(Object)": {
                    "type": "string"
                },
                "remove(Object, Object)": {
                    "type": "boolean"
                },
                "removeNode(int, Object, Object, boolean, boolean)": {
                    "$ref": "#/definitions/Node(String,String)"
                },
                "replace(String, String)": {
                    "type": "string"
                },
                "replace(String, String, String)": {
                    "type": "boolean"
                },
                "replacementNode(Node<String, String>, Node<String, String>)": {
                    "$ref": "#/definitions/Node(String,String)"
                },
                "replacementTreeNode(Node<String, String>, Node<String, String>)": {
                    "$ref": "#/definitions/TreeNode(String,String)"
                },
                "resize()": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Node(String,String)"
                    }
                },
                "size()": {
                    "type": "integer"
                },
                "toString()": {
                    "type": "string"
                },
                "values()": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": {
                "type": "string"
            }
        },
        "Node(String,String)": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
               "equals(Object)": {
                    "type": "boolean"
                },
                "hashCode()": {
                    "type": "integer"
                },
                "setValue(String)": {
                    "type": "string"
                },
                "toString()": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "TreeNode(String,String)": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "equals(Object)": {
                    "type": "boolean"
                },
                "find(int, Object, Class<Object>)": {
                    "$ref": "#/definitions/TreeNode(String,String)"
                },
                "getTreeNode(int, Object)": {
                    "$ref": "#/definitions/TreeNode(String,String)"
                },
                "hashCode()": {
                    "type": "integer"
                },
                "putTreeVal(HashMap<String, String>, Node[]<String, String>, int, String, String)": {
                    "$ref": "#/definitions/TreeNode(String,String)"
                },
                "root()": {
                    "$ref": "#/definitions/TreeNode(String,String)"
                },
                "setValue(String)": {
                    "type": "string"
                },
                "toString()": {
                    "type": "string"
                },
                "untreeify(HashMap<String, String>)": {
                    "$ref": "#/definitions/Node(String,String)"
                }
            },
            "additionalProperties": false
        }
    },
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "title": "Code",
                "description": "A 3 letter Area code.",
                "minLength": 3,
                "maxLength": 3
            },
            "extendedDTO": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "name": {
                        "$ref": "#/definitions/LowerCaseHashMap(String)"
                    }
                },
                "additionalProperties": false
            },
            "name": {
                "allOf": [{
                        "$ref": "#/definitions/LowerCaseHashMap(String)"
                    }, {
                        "title": "Name",
                        "description": "The name of the Area, in different languages. Each langauge, should be a 2 letter ISO language code.",
                        "uniqueItems": true
                    }
                ]
            },
            "compareTo(AreaCode)": {
                "type": "integer"
            },
            "toString()": {
                "type": "string"
            }
        },
        "required": ["code", "name"],
        "title": "Area Code",
        "description": "Area Code, for describing an area in the world ex. Europe, Africa etc.",
        "additionalProperties": false
    }
}

Br
Casper

**Comment by CarstenWickner** [comment]
Hi Casper,

If you want to get rid of all these extra methods being documented, you'll have to configure `configBuilder.forMethods().withIgnoreCheck()` accordingly.

Would be great if you could provide a minimal reproducible example, in order to determine why the particular `getChildNodes()` method you were aiming for is still not included.

**Comment by CathKilroy** [comment]
Hi

Thanks for your help. I solved it with .withIgnoreCheck. I had hoped, I could solve it, and still keep the inline definitions. For now, we live with definition ref’s.

Thanks for your help, and the great tool you have made.

Br
Casper

**Comment by CarstenWickner** [comment]
Hi Casper,

Now that you're excluding some of those entries, the circular dependency might be gone as well.
You can at least try to add the `Option.INLINE_ALL_SCHEMAS` again. 😉

**Comment by CathKilroy** [comment]
And that worked to 😊 And everyone will be happy 😃

/Casper
