### ISSUE TITLE
How about implement a gradle/maven plugin?

### ISSUE THREAD

**Issue by rainmanhhh** [victools/jsonschema-generator#151]

**Comment by CarstenWickner** [comment]
Hi @rainmanhhh,

There is already a Maven Plugin: https://github.com/victools/jsonschema-generator/blob/master/jsonschema-maven-plugin

As to a Gradle Plugin, please refer to the example given in GH-144.

**Comment by CarstenWickner** [comment]
It's now also explicitly mentioned in the documentation:
- https://victools.github.io/jsonschema-generator/#maven-plugin
- https://victools.github.io/jsonschema-generator/#is-there-a-gradle-plugin
