### ISSUE TITLE
Build Failure on Generate JSONSchema

### ISSUE THREAD

**Issue by brunoselva** [victools/jsonschema-generator#159]
Apache Maven 3.6.1
Java 8

`<build>
  <plugin>
    <groupId>com.github.victools</groupId>
    <artifactId>jsonschema-maven-plugin</artifactId>
    <version>4.17.0</version>
    <executions>
	    <execution>
		    <goals>
			    <goal>generate</goal>
		    </goals>
	    </execution>
    </executions>
  </plugin>
</build>`

Could not find artifact com.github.victools.jsonschema-generator:jsonschema-generator:jar:4.17.0 in central (https://repo.maven.apache.org/maven2)

Any idea why?

**Comment by CarstenWickner** [comment]
Hi @brunoselva,

Can you please try again?
When following the link in the error message, I can find the artifact:
https://repo.maven.apache.org/maven2/com/github/victools/jsonschema-generator/4.17.0/
