### ISSUE TITLE
Support for @JsonProperty(required=..) and @JsonFormat [Jackson Module]

### ISSUE THREAD

**Issue by jjmbourdaret** [victools/jsonschema-generator#162]
Hi, thanks for this great lib !

There is several options for checking wether or not a field has to be tagged as "required", they are currently based on @Nullable and other validations Options.

Could it be possible to support `@JsonProperty(required=true)` in the **jacksonModule** ?
also, having some control over the format would be nice, `@JsonFormat` may be of some use to address this.

Here is the code I use for `required` :+1: 
```java
Module requiredModule = requiredBuilder -> schemaConfigBuilder
        .forFields().withRequiredCheck(field -> {
            JsonProperty jsonProperty = field.getAnnotationConsideringFieldAndGetter(JsonProperty.class) ;
            if ( jsonProperty == null )
                return false;
            else
                return jsonProperty.required();
        }) ;
```
using 4.17.0

**Comment by CarstenWickner** [comment]
Hi @jjmbourdaret,

Supporting the `@JsonProperty(required=true)` flag should be straightforward as per your code sample. Including this via a standard `JacksonOption` is a good idea, I'm just not sure when I'll get around to introduce it. I'm open for a PR though. Until then, the configuration seems easy enough that it won't make much of a difference either way.

As to the `@JsonFormat`: that offers a considerable degree of flexibility. It won't be easy to fully support. Again, I'm open for a PR but I'm afraid that won't be as straightforward. Specifically configuring something for the one/two use-cases in one's code base is much simpler than aiming at support for all the different aspects the JavaDoc is already hinting at:
> **`public @interface JsonFormat`**
> General-purpose annotation used for configuring details of how values of properties are to be serialized. Unlike most other Jackson annotations, annotation does not have specific universal interpretation: instead, effect depends on datatype of property being annotated (or more specifically, deserializer and serializer being used).
> 
> Common uses include choosing between alternate representations -- for example, whether Date is to be serialized as number (Java timestamp) or String (such as ISO-8601 compatible time value) -- as well as configuring exact details with pattern() property.
> 
> As of Jackson 2.6, known special handling includes:
> - Date: Shape can be JsonFormat.Shape.STRING or JsonFormat.Shape.NUMBER; pattern may contain SimpleDateFormat-compatible pattern definition.
> - Can be used on Classes (types) as well, for modified default behavior, possibly overridden by per-property annotation
Enums: Shapes JsonFormat.Shape.STRING and JsonFormat.Shape.NUMBER can be used to change between numeric (index) and textual (name or toString()); but it is also possible to use JsonFormat.Shape.OBJECT to serialize (but not deserialize) Enums as JSON Objects (as if they were POJOs). NOTE: serialization as JSON Object only works with class annotation; will not work as per-property annotation.
> - Collections can be serialized as (and deserialized from) JSON Objects, if JsonFormat.Shape.OBJECT is used. NOTE: can ONLY be used as class annotation; will not work as per-property annotation.
> - Number subclasses can be serialized as full objects if JsonFormat.Shape.OBJECT is used. Otherwise the default behavior of serializing to a scalar number value will be preferred. NOTE: can ONLY be used as class annotation; will not work as per-property annotation.

**Comment by jjmbourdaret** [comment]
Thanks @CarstenWickner for the detailed answer !
I submitted a PR to enable the `@JsonProperty(required...)` part of this issue.
About `@JsonFormat` , you're right, this might get too complicated, 
and I achieve some of its features with the help of the `JavaxValidationModule` anyway

**Comment by CarstenWickner** [comment]
The PR is merged and will be part of the next release. Since your configuration given above is simple enough, I'll not release it just for this one change yet.

Supporting `@JsonFormat` would be nice, but I lack the spare time to dive into it right now.

Closing this ticket for now, but feel free to log a new one for the `@JsonFormat` alone, maybe someone will provide a PR for it.

**Comment by jjmbourdaret** [comment]
Thank you , 
I agree, no need to make a new release; this was simple enough to introduce me to PR ;)
