### ISSUE TITLE
Change Property Names to apply Snake Case

### ISSUE THREAD

**Issue by trixoflow** [victools/jsonschema-generator#169]
hi :)

i have this class
```
public class Foo {
  private String aVariable
}
```
The input in rest level would be 
```
{
  "a_variable" : "1"
}
```
How do I create a schema that has snake case properties? I was thinking about manipulating the ObjectMapper, but it seems that is immutable

**Comment by CarstenWickner** [comment]
Hi @trixoflow,

That'd be a job for a "Property Name Override":
- https://victools.github.io/jsonschema-generator/#names-of-fields-methods-in-an-object-39-s-properties

For snake case, in particular, you can find an example in the unit tests that makes use of the built-in Jackson naming strategies:
```java
NamingBase jacksonSnakeCase = (NamingBase) PropertyNamingStrategies.SNAKE_CASE;
SchemaDefinitionNamingStrategy snakeCase = new DefaultSchemaDefinitionNamingStrategy() {
    @Override
    public String getDefinitionNameForKey(DefinitionKey key, SchemaGenerationContext generationContext) {
        return jacksonSnakeCase.translate(super.getDefinitionNameForKey(key, generationContext))
            .replaceAll("<_", "<")
            .replaceAll(", _", ",");
    }
};
```
https://github.com/victools/jsonschema-generator/blob/040515b6a60ebf29b0f22de2d9c89d4182c6c596/jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/naming/SchemaDefinitionNamingStrategyTest.java#L62-L70

**Comment by trixoflow** [comment]
Hi Carsten, thank you for the lightning speed response. I have seen the SchemaDefinitionNamingStrategy, but as I understand it only changing the class name to snake, not the properties, maybe I am missing something?

I tried the Property Name Override and it partially suits the purpose. I say partially, because write now, I am manually transforming all properties from camel to snake. Although this won't cause any problems in the system as it currently is, I would prefer to read the @JsonNaming annotation in the class and do it automatically. 

I think what I am asking for is a what your example is doing for JsonProperty, but in a class level for JsonNaming. Can it be done?

Again thank you very much for the super quick response.

**Comment by CarstenWickner** [comment]
Hi @trixoflow,

You're absolutely right. As the name suggests, a `SchemaDefinitionNamingStrategy` is meant to affect the keys in the `"$defs"`/`"definitions"` and nothing else. I selected the wrong examples above. 🤦 Sorry for that.

But what you're asking for is actually the out-of-the-box behavior of the [`JacksonModule`](https://victools.github.io/jsonschema-generator/#jackson-module).
I suggest you include that module and see whether it matches your expectations.

Internally, it uses Property Name Overrides, i.e. at least the link to the documentation was the right one. 😀
https://github.com/victools/jsonschema-generator/blob/040515b6a60ebf29b0f22de2d9c89d4182c6c596/jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java#L182-L195

**Comment by erodewald** [comment]
@CarstenWickner 
I hate to reopen this arbitrarily but want to avoid creating a duplicate issue. I have a similar concern, where I would like to apply `snake_case` across the board for **property names**. I wanted to steer clear of using the Jackson module and have taken a liking to the `jsonSchema` module add-on. To improve developer adoption internally, I don't want to decorate each field manually, or even at the class level. 

I validated that decorating the class with `@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)` _does_ work. 

Is there a reason to not support setting this value on the `ObjectMapper`? 

e.g.,
```java
objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(objectMapper, ....)
```

It would appear that the mapper is not respected for generation. Do you have a suggestion on proper configuration? Or some guidance on a pull request?

**Comment by CarstenWickner** [comment]
Hi @erodewald,

The `ObjectMapper` is purely used for generating the JSON Schema document, not for analyzing how a given Java type should be transferred into the JSON Schema.

The standard modules (like the `JacksonModule` are merely a combination of individual configurations. If you don't like to use this preset of Jackson-related configurations, you can easily copy-paste the parts you are interested in (as per the linked section in my previous comment) and ignore the rest.

For your particular use-case of globally applying "Snake Case" you can make it even simpler, by skipping the look-up step and go straight for the `withPropertyNameOverrideResolver()` configuration.

- for Jackson 2.12+
```java
PropertyNamingStrategies.SnakeCaseStrategy snakeCase = new PropertyNamingStrategies.SnakeCaseStrategy();
fieldConfigPart.withPropertyNameOverrideResolver(field -> snakeCase.translate(field.getName()));
```
- for Jackson below 2.12
```java
PropertyNamingStrategy.SnakeCaseStrategy snakeCase = new PropertyNamingStrategy.SnakeCaseStrategy();
fieldConfigPart.withPropertyNameOverrideResolver(field -> snakeCase.translate(field.getName()));
```

**Comment by erodewald** [comment]
Ahhh, thank you @CarstenWickner 🎉 Those are the missing pieces of the puzzle for me. By using the aforementioned propertyNameOverrideResolver, it works well across all of my test cases.
