### ISSUE TITLE
Swagger 1.5 module not removing allOf

### ISSUE THREAD

**Issue by PovilasSlekys** [victools/jsonschema-generator#184]
Hello,

I am trying to generate a JSON schema from classes annotated with Swagger 1.5 @ApiModelProperty to include the description in the schema, but I end up with all my schemas containing these allOf structures:

```
"allOf" : [ {
                    "$ref" : "#/definitions/SomeClass"
                  }, {
                    "description" : "Some class description."
                  } ]
```

The tools I am using to generate code from schema down the line do not support allOf so I would like to try to get rid of this.
However neither specifying the OptionPreset.PLAIN_JSON nor specifying Option.ALLOF_CLEANUP_AT_THE_END seems to help.

Any help on the matter would be appreciated.

**Comment by CarstenWickner** [comment]
Hi @PovilasSlekys,

What JSON Schema Version are you targeting?
Only with the latest Draft Version is it allowed to combine `$ref` with any other keywords.
For older versions, the `allOf` is necessary.

Cheers,
Carsten

**Comment by PovilasSlekys** [comment]
Hello Carsten,

you are correct I was using the DRAFT 7 version.
Thank you for the help!
