### ISSUE TITLE
Maven Plugin : change property type according to JsonSerialize

### ISSUE THREAD

**Issue by FlorianAgilap** [victools/jsonschema-generator#189]
**Version used : *4.18.0***

Hello,

We are using the JSON Schema Generator Maven Plugin in our project.

One of our classes uses Java's `BigDecimal` with a custom serializer `MyStringSerializer`, such as this :
```Java
import java.math.BigDecimal;

import javax.validation.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.mycompany.common.utils.MyStringSerializer;

public class MyClass {
  @NotEmpty
  @JsonProperty(required = true)
  @JsonSerialize(using = MyStringSerializer.class)
  public BigDecimal balance;
}
```

```Java
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;

public class MyStringSerializer extends JsonSerializer<BigDecimal> {
    @Override
    public void serialize(BigDecimal value, JsonGenerator jgen, SerializerProvider provider)
            throws IOException, JsonProcessingException {
        jgen.writeString(value.setScale(2, RoundingMode.HALF_EVEN).toString());
    }
}
```

Jackson then correctly serializes the value to a `String`, but unfortunately the JSON Schema that is generated still considers it a `number` :

```JSON
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "balance" : {
      "type" : "number"
    }
  },
  "required" : [ "balance"]
}
```

I haven't been able to find a way to tell the generator that this field is a special case. I checked the Github issues and I found #127 but it doesn't use the Maven Plugin.

Is there a way to make the generator behave how I want ?

I am open to many kind of solutions : Maven Plugin configuration, Java annotation, ...

Thanks in advance !

**Comment by CarstenWickner** [comment]
Hi @FlorianAgilap,

Just in short (due to limited capacity on my part right now): what you want to do:
- create a small `Module` that includes a custom definition provider either for `BigDecimal` in general or just for the affected classes including it
- in the Maven Plugin configuration add your own module

For some more explanation please refer to the documentation.

**Comment by FlorianAgilap** [comment]
Hello, thanks for the help!
