### ISSUE TITLE
Add support for accessMode to Swagger2Module

### ISSUE THREAD

**Issue by jochenberger** [victools/jsonschema-generator#193]
`accessMode = Schema.AccessMode.READ_ONLY` is currently ignored in  `@Schema` annotations.

**Comment by CarstenWickner** [comment]
Thanks for logging this.
This should be straightforward to add.

Since `"readOnly"` and `"writeOnly"` are currently not supported in general though, that'd need to be part of the change here as well then, i.e., not just the Swagger Module.

**Comment by CarstenWickner** [comment]
Hi @jochenberger,

This has been released in [v4.19.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.19.0) now.
