### ISSUE TITLE
Add generated files as project artifacts

### ISSUE THREAD

**Issue by juherr** [victools/jsonschema-generator#203]
Hi,

At least with Maven, it could be helpful to have an option that adds all created schema as artifacts of the module.

As workaround, I'm using https://www.mojohaus.org/build-helper-maven-plugin/attach-artifact-mojo.html

**Comment by CarstenWickner** [comment]
Hi @juherr,

Can you elaborate what it is exactly you mean?
In case of the Maven Plugin, you can specify the target directory for the generated schemas.
If that target directory is marked as a source directory, those schemas should end up in your artifact/classpath.

What else did you have in mind?

**Comment by juherr** [comment]
I'm trying to share the definition of messages between microservices and jsonschema could be a solution.

That's why I want to deploy the jsonschemas as artifacts of the project.

Using build-helper-maven-plugin will work but I need to configure every jsonschema one by one (or zip all before).
