### ISSUE TITLE
Support for default values

### ISSUE THREAD

**Issue by eitzenbe** [victools/jsonschema-generator#211]
Hi Carsten,
Awesome lib and loved to use it, but currently I am lacking the info (mainly for boolean) of the default value to be present somehow in the schema...
Is this something already existing (and I am too blind to see)?
or is there any plan to add it near term?
or am I lost here?

br
Thomas

**Comment by CarstenWickner** [comment]
HI @eitzenbe,

Thanks for the kind words.

This has come a few times already. Please refer to the documentation:
https://victools.github.io/jsonschema-generator/#how-to-populate-default-values

> The short answer is: via the `withDefaultResolver()` – one of the [Individual Configurations](https://victools.github.io/jsonschema-generator/#generator-individual-configurations).
> The exact details depend on how the `default` value can be determined.
> 
> - If the `defaul`t value is explicitly stated via some kind of annotation, it might be as simple as "Example 1" on the right.
> - If the `default` value is only set in code, and you cannot or don't want to maintain that piece of information twice this can get a bit more advanced. Here assuming your own classes all have a default no-args constructor and conventional getters as in "Example 2" [below].
> 
> ### Example 1
> 
```java
configBuilder.forFields().withDefaultResolver(field -> {
    JsonProperty annotation = field.getAnnotationConsideringFieldAndGetter(JsonProperty.class);
    return annotation == null || annotation.defaultValue().isEmpty() ? null : annotation.defaultValue());
});
```
> ### Example 2
```java
ConcurrentMap<Class<?>, Object> instanceCache = new ConcurrentHashMap<>();
configBuilder.forFields().withDefaultResolver(field -> {
    Class<?> declaringClass = field.getDeclaringType().getErasedType();
    if (!field.isFakeContainerItemScope()
            && declaringClass.getName().startsWith("your.package")) {
        MethodScope getter = field.findGetter();
        if (getter != null) {
            try {
                Object instance = instanceCache.computeIfAbsent(declaringClass, declaringClass::newInstance);
                Object defaultValue = getter.getRawMember().invoke(instance);
                return defaultValue;
            } catch (Exception ex) {
                // most likely missing a no-args constructor
            }
        }
    }
    return null;
});
```
