### ISSUE TITLE
Cannot use getAnnotationConsideringFieldAndGetter for invisibleTypeAnnotations like org.eclipse.jdt.annotation.Nullable

### ISSUE THREAD

**Issue by marcelrv** [victools/jsonschema-generator#219]
The getAnnotationConsideringFieldAndGetter() utility helps with getting the regular annotations. However, for certain annotations that are not available at runtime like  org.eclipse.jdt.annotation.Nullable they are always returning null.

see below example code... the getAnnotationConsideringFieldAndGetter always return null, 
The remaining code finds the annotation even if it is hidden by examining the class.

Probaly there are better ways to archieve this, but for now this seem to do the trick for me. Maybe it helps someone else as well.

```
\\imports required to get this working
import org.objectweb.asm.tree.AnnotationNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.TypeAnnotationNode;

\\example 
        configBuilder.forFields().withRequiredCheck(field -> {
            logger.debug("Regular lookup for {} -> {} & {}", field.getDeclaredName(),
                    field.getAnnotationConsideringFieldAndGetter(Nullable.class),
                    field.getContainerItemAnnotationConsideringFieldAndGetterIfSupported(
                            org.eclipse.jdt.annotation.Nullable.class));

            String searchAnnotation = "Nullable";
            try {
                ClassNode cn = new ClassNode();
                ClassReader reader = new ClassReader(field.getDeclaringType().getBriefDescription());
                reader.accept(cn, 0);
                logger.trace("Class Name : {}", cn.name);
                logger.trace("Source File : {}", cn.sourceFile);
                for (FieldNode f : cn.fields) {
                    if (f.name.contentEquals(field.getDeclaredName())) {
                        List<TypeAnnotationNode> annotationList = f.invisibleTypeAnnotations;
                        if (annotationList != null && !annotationList.isEmpty()) {
                            AnnotationNode ret = annotationList.stream()
                                    .filter(an -> an.desc.contains(searchAnnotation)).findFirst().orElse(null);
                            logger.debug("InvisibleTypeAnnotations Lookup for {} : Annotation '{}' found: {}. Full: {}",
                                    field.getDeclaredName(), searchAnnotation, ret != null,
                                    ret != null ? ret.desc : "n/a");
                            return ret != null;
                        }
                    }
                }
            } catch (IOException e) {
                logger.info("Error getting class: {}", e.getMessage(), e);
            }
            return false;
        });
```

java example of the class
```
    @Schema(description = "Channel Id")
    @SerializedName("channel")
    @Expose
    private String channel = "";
    @SerializedName("Channel description")
    @Expose
    private @Nullable String description;
```

output example.. the middle line shows that getAnnotationConsideringFieldAndGetter() does not 'see' the `@Nullable` even though it is there.

```
2021-12-19 19:55:20:342 DEBUG docu - Regular lookup for channel -> null & null
2021-12-19 19:55:20:344 DEBUG docu - Regular lookup for description -> null & null
2021-12-19 19:55:20:346 DEBUG docu - InvisibleTypeAnnotations Lookup for description : Annotation 'Nullable' found: true. Full: Lorg/eclipse/jdt/annotation/Nullable;
```

**Comment by CarstenWickner** [comment]
Hi @marcelrv,

Thanks for sharing your solution.

I feel like the `org.eclipse.jdt.annotation.Nullable` annotation with its `RetentionPolicy.CLASS` (i.e., it's only visible to a compiler but not afterward) doesn't want to be detected at runtime.

The external library requires source code access in order to do its "magic" and would therefore not work in a separate project, where the code from which the schema is being generated is merely pulled in as a dependency.

That's a big limitation and I'd (personally) prefer to get rid of that annotation then.
But it comes down to personal taste.
In my world, everything is assumed to be nullable only explicitly stated otherwise (as `@NotNull`), thereby avoiding a forgotten annotation giving me a false sense of safety, i.e., tempting me to omit the necessary `null` check.

**Comment by marcelrv** [comment]
Fully agree with your comments.

In my situation, the project requires to use the org.eclipse.jdt.annotation, so not so much a personal taste, but instead the direction of the project.

Note that indeed you typically mark the whole class as `@NonNullByDefault` , hence this is why my sample codes works for me while only checking for `@Nullable`, and don't try to find out if something is `@NotNull` ... In case the class is not marked as `@NonNullByDefault` , the code would need to be extended to deal with that)
