### ISSUE TITLE
Add Maven Bill of Materials (aka bom)

### ISSUE THREAD

**Issue by paskos** [victools/jsonschema-generator#225]
Documentation states
_It is recommended to use identical versions for all of them to ensure compatibility._

Version compatibility would be made easier and less error prone if json-schema-generator had a [Maven Bill of material](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms)

**Comment by CarstenWickner** [comment]
Hi @paskos,

Good hint. I've personally simply used a version variable in my `pom.XML` for that purpose, but adding a BOM is probably no inconvenience either.
Will add it at some point (likely starting with next release then).

**Comment by CarstenWickner** [comment]
As of [v4.24.2](https://github.com/victools/jsonschema-generator/releases/tag/v4.24.2), the BOM is now a proper part of the regular builds.
