### ISSUE TITLE
Include FQCN (fully qualified class name) in JSON schema

### ISSUE THREAD

**Issue by lud** [victools/jsonschema-generator#231]
Hi, 

I work with a team of Java developers, and we use JSON Schemas to normalize data that is sent over Kafka. 

My application is not Java. They ask me to send the FQCN of the serialized object when sending JSON payloads in Kafka.

As I am generating code from the JSON schemas, I think I could store that FQCN somewhere in the generated code, so it is available when I normalize and serialize the payloads. That is, if I can find that FQCN when generating the code. So I would like it to be present in the schema directly.

Is there a way to do that? I was thinking of adding a custom field in the schema, for instance `$fqcn` (at the top level just like `"$schema" : "http://json-schema.org/draft-07/schema#"`.)

If possible, would it be also possible to include it for all embedded objects (objects that are in a property of a parent object and described in the `properties` object of the schema).

Thank you.

**Comment by CarstenWickner** [comment]
Hi @lud,

This is certainly possible.
Your requirements sounds pretty much like the example given here: https://victools.github.io/jsonschema-generator/#instance-attribute-overrides

You can then adjust it accordingly to something like this:
```java
configBuilder.forTypesInGeneral()
    .withTypeAttributeOverride((node, scope, context) -> node
            .put("$fqcn", scope.getType().getErasedType().getName()));
```
This would apply to all type definitions, i.e., the main schema as well as all nested types.

**Comment by lud** [comment]
Works like a charm, thank you very much!

**Comment by lud** [comment]
Hi, 

I am following the docs, even reading java code, but I cannot manage to do one more thing.

We are using `JsonSubTypes` for referencing implementations of a property based on the value of another property:

```
  @NotEmpty
  @JsonProperty(required = true)
  public Category category;

  @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "category", include = JsonTypeInfo.As.EXTERNAL_PROPERTY)
  @JsonSubTypes(value = {
      @JsonSubTypes.Type(value = CategoryAAAData.class, name = "CAT_AAA"),
      @JsonSubTypes.Type(value = CategoryBBBData.class, name = "CAT_BBB"),
  })
  public ICategoryData categoryData;
  ```
  
  This generates a schema node like this: `{"anyOf": [...]}`
  
  I would like to write the mapping of names to FQCNs in that node, so I would get:
  
  ```
  {
    "anyOf": [...], 
    "$mappedType": {
        "discr": "category", 
        "mapping": {
            "CAT_AAA": fqcn of CategoryAAAData,
            "CAT_BBB": fqcn of CategoryBBBData
        }
    }
}
```

I am trying to use `.withCustomDefinitionProvider`, `.withInstanceAttributeOverride`, `.withSubtypeResolver` and `.withTypeAttributeOverride` on general types or fields but the node containing the `TAG_ANYOF` never gets passed to me.

Although it looks like the definition of that node is generated [here](https://github.com/victools/jsonschema-generator/blob/7c326115d6d8278b0f0b939532446932dbd750a2/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java#L305) and should be passed to my callbacks [here](https://github.com/victools/jsonschema-generator/blob/7c326115d6d8278b0f0b939532446932dbd750a2/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java#L318).

But that specific kind of node I dont see it pass through my own code.

Do you know if there is a way of doing whay I am trying to do?

Thank you.

**Comment by CarstenWickner** [comment]
Hi @lud,

A `CustomDefinitionProvider` is the right choice.
Please find below a working simplified example.
Especially note the `context.createStandardDefinition(javaType, this)` in the `CustomDefinitionProvider`, which is the point where the node containing the `"anyOf"` is being created.

```java
import com.fasterxml.classmate.ResolvedType;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.github.victools.jsonschema.generator.CustomDefinition;
import com.github.victools.jsonschema.generator.CustomDefinitionProviderV2;
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.SchemaGenerationContext;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfig;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaVersion;
import com.github.victools.jsonschema.module.jackson.JacksonModule;

public class JacksonSubtypesExample3 {

    public static void main(String[] args) {
        SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON);
        configBuilder
                .with(new JacksonModule())
                .forTypesInGeneral()
                .withCustomDefinitionProvider(new SubTypeContextDefinitionProvider());
        SchemaGeneratorConfig config = configBuilder.build();
        SchemaGenerator generator = new SchemaGenerator(config);
        JsonNode jsonSchema = generator.generateSchema(Data.class);

        System.out.println(jsonSchema.toPrettyString());
    }

    private static class SubTypeContextDefinitionProvider implements CustomDefinitionProviderV2 {

        @Override
        public CustomDefinition provideCustomSchemaDefinition(ResolvedType javaType, SchemaGenerationContext context) {
            JsonTypeInfo typeInfoAnnotation = javaType.getErasedType().getAnnotation(JsonTypeInfo.class);
            if (typeInfoAnnotation == null) {
                return null;
            }
            JsonSubTypes subTypesAnnotation = javaType.getErasedType().getAnnotation(JsonSubTypes.class);
            if (subTypesAnnotation == null) {
                return null;
            }
            ObjectNode standardDefinition = context.createStandardDefinition(javaType, this);
            ObjectNode mappingNode = standardDefinition.with("$mappedType")
                    .put("discr", typeInfoAnnotation.property())
                    .with("mapping");
            for (JsonSubTypes.Type subType : subTypesAnnotation.value()) {
                mappingNode.put(subType.name(), subType.value().getName());
            }
            return new CustomDefinition(standardDefinition, CustomDefinition.DefinitionType.STANDARD, CustomDefinition.AttributeInclusion.NO);
        }
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "category")
    @JsonSubTypes({
        @JsonSubTypes.Type(value = CategoryAAAData.class, name = "CAT_AAA"),
        @JsonSubTypes.Type(value = CategoryBBBData.class, name = "CAT_BBB")
    })
    public static abstract class Data {
        private String category;
    }

    @JsonTypeName("CAT_AAA")
    public static class CategoryAAAData extends Data { }

    @JsonTypeName("CAT_BBB")
    public static class CategoryBBBData extends Data { }
}
```

The resulting output is:

```json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "anyOf" : [ {
    "type" : "object",
    "properties" : {
      "category" : {
        "const" : "CAT_AAA"
      }
    }
  }, {
    "type" : "object",
    "properties" : {
      "category" : {
        "const" : "CAT_BBB"
      }
    }
  } ],
  "$mappedType" : {
    "discr" : "category",
    "mapping" : {
      "CAT_AAA" : "com.github.victools.example.JacksonSubtypesExample3$CategoryAAAData",
      "CAT_BBB" : "com.github.victools.example.JacksonSubtypesExample3$CategoryBBBData"
    }
  }
}
```

**Comment by lud** [comment]
Hi @CarstenWickner , thank you very much to take the time to look into this.

Unfortunately, while a custom definition or custom attributes allows me to add anything I want to the nodes that are passed to me, the node containing the `anyOf` list is never passed as an argument to my callback. Its siblings get passed.

I also tried with `.forFields().withCustomDefinitionProvider` and an implementation with a private subclass like you showed me, with the same results. This time I can add stuff even to string or numeral properties, but never on anyof.

We use the maven plugin ; I tried to disable any configuration or other modules but it doesn't change much. Unfortunately I cannot show some code. I will try to make a small demo project when I find the time to do so.

**Comment by CarstenWickner** [comment]
Hi @lud,

It seems you want to do something else besides the mapping above.
A few notes on your observation:

1. When you invoke `context. createStandardDefinitionReference()`, you will receive an empty `ObjectNode`, which will only be filled at a later stage (either with a `$ref` or an inline schema, e.g., containing the `anyOf` property).
2. The `TypeAttributeOverride` receives the already filled online schema as input, i.e., there you should be able to find the `anyOf`.
3. Due to the involved complexity, the received input for the `TypeAttributeOverride` may still contain unneeded extra `allOf`/`anyOf` wrappers around the part you're looking for. Those are only being cleaned up at the very end of the process, which you can currently toggle on/off but not influence any further.

All in all, a minimum working example would be very helpful in order to provide specific assistance.

**Comment by lud** [comment]
Yes ! Please find a demo example here : https://github.com/lud/victools-fqcn-demo

**Comment by CarstenWickner** [comment]
I can confirm that neither `CustomDefinitionProvider`/`CustomPropertyDefinitionProvider` nor `TypeAttributeOverride`/`InstanceAttributeOverride` currently receives the node directly containing the `"anyOf"` on a respective property.

That is currently due to your overriding of the applicable subtypes on the respective fields instead of declaring it on the `IPage` interface type in general. Please also note that `include = JsonTypeInfo.As.EXTERNAL_PROPERTY` is currently not supported. The external property will not be added/defined correctly in the schema!

As to accessing the `"anyOf"`: I guess I could change it so that at least the `InstanceAttributeOverride` is being applied there again (in addition to being applied on each subtype version of the property).
This combination is likely not used so widely yet to prohibit this. May need to consider indicating in some obvious manner, when a given property schema is (a) the declared type without any subtypes being applied, (b) an overridden subtype, (c) the declared type but where subtypes exist as well.

For now, you could work around this limitation by utilizing a `TypeAttributeOverride` and then iterating over its properties – checking whether any of them contain an `"anyOf"` directly. But I can appreciate it if that's not a feasible option for you.

Either way, would be worth creating a separate issue for this, as the original question here for the fully qualified class name being included (in most circumstances) has been answered.

**Comment by lud** [comment]
> I can confirm that neither CustomDefinitionProvider/CustomPropertyDefinitionProvider nor TypeAttributeOverride/InstanceAttributeOverride currently receives the node directly containing the "anyOf" on a respective property.

OK !

> Please also note that include = JsonTypeInfo.As.EXTERNAL_PROPERTY is currently not supported. The external property will not be added/defined correctly in the schema!
 
In our classes we add the JSON annotation to the properties so those discriminant properties so I guess that is not a limitation for us, they are present in the schema, for instance : https://github.com/lud/victools-fqcn-demo/blob/1fed3ffb9239782cf192e0a20d818134d1c6f6f0/src/main/resources/schemas/CreatePage-schema.json#L6

> As to accessing the "anyOf": I guess I could change it so that at least the InstanceAttributeOverride is being applied there again (in addition to being applied on each subtype version of the property).
This combination is likely not used so widely yet to prohibit this. May need to consider indicating in some obvious manner, when a given property schema is (a) the declared type without any subtypes being applied, (b) an overridden subtype, (c) the declared type but where subtypes exist as well.

As you may have guessed, we are not really using the generated schemas to be used as actual JSON schemas. We just need a language agnostic definition of some data structures, and victools is really helpful for it. So I would not bother change the library just for that specific use case ; but hey, If you think it can be useful for other purposes, why not.

> For now, you could work around this limitation by utilizing a TypeAttributeOverride and then iterating over its properties – checking whether any of them contain an "anyOf" directly. But I can appreciate it if that's not a feasible option for you.

That was kind of hard because of my limited knowledge of java but I got it to work with your suggestions : https://github.com/lud/victools-fqcn-demo/blob/1fed3ffb9239782cf192e0a20d818134d1c6f6f0/src/main/java/com/myapp/contracts/serialization/FqcnModule.java#L35

Thanks a lot!
