### ISSUE TITLE
jackson-module not applying @JsonIgnoreProperty on inherited properties

### ISSUE THREAD

**Issue by samortiz** [victools/jsonschema-generator#235]
Given this class structure
```
public class Parent {
    public String parentField;
}

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties({ "parentField"})
public class Child extends Parent {
    public String childField;
}
```

And this code to generate a schema: 
```
JacksonModule jacksonModule = new JacksonModule();
SchemaGeneratorConfig config =
    new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
        .with(Option.NULLABLE_FIELDS_BY_DEFAULT)
        .with(jacksonModule)
        .build();
SchemaGenerator generator = new SchemaGenerator(config);
return generator.generateSchema(Child.class);
```

I get this schema generated : 
```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "childField": {
      "type": [
        "string",
        "null"
      ]
    },
    "parentField": {
      "type": [
        "string",
        "null"
      ]
    }
  }
}
```
I would expect parentField to not be in the schema as the @JsonIgnoreProperties should be respected. 

Jackson ObjectMapper works as expected and excludes parentField : 
```
Child c = new Child();
c.parentField = "parent";
c.childField = "child";
ObjectMapper mapper = new ObjectMapper();
System.out.println(mapper.writeValueAsString(c));
Output : 
{"childField":"child"}
```

I found that @JsonIgnoreProperties DOES work for fields that are included in the class (childField in this case), but NOT for fields inherited from a parent class. 

I am using  these versions: 
```
<jsonschema.generator.version>4.23.0</jsonschema.generator.version>
<jsonschema.module.jackson.version>4.23.0</jsonschema.module.jackson.version>
<victools.jsonschema.version>4.23.0</victools.jsonschema.version>
```

**Comment by CarstenWickner** [comment]
Hi @samortiz,

Thanks for reporting this.
Now that you point out that possibility, this line appears to be responsible:
https://github.com/victools/jsonschema-generator/blob/14b43c8d938e2569bbef2ecc2e4307a26c187a03/jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java#L260

There, only the directly declaring type is being considered, not the actual (sub)type the schema is for.
I may have to extend the `FieldScope` to pass through that actual (sub)type as it may now require some (hacky) workaround to achieve.

Not sure when I'll have the capacity to look into this myself, but a pull request is always welcome. 😃

**Comment by CarstenWickner** [comment]
The fix actually seems straightforward:
https://github.com/victools/jsonschema-generator/pull/236/files#diff-222e2e4d7e057626889399a014d6ad047b76725fa3d5b824d23263550e2b0476R261-R262
