### ISSUE TITLE
@JsonPropertyOrder does not work with for inherited fields

### ISSUE THREAD

**Issue by mikezerosix** [victools/jsonschema-generator#243]
```Java
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.github.victools.jsonschema.generator.*;
import com.github.victools.jsonschema.module.jackson.*;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class JsonSchemaGeneratorTest {

  private SchemaGenerator getSchemaGenerator() {
    JacksonModule moduleJackson = new JacksonModule(JacksonOption.RESPECT_JSONPROPERTY_ORDER);
    SchemaGeneratorConfigBuilder config = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_7, OptionPreset.PLAIN_JSON).with(moduleJackson);
    return new SchemaGenerator(config.build());
  }

  @Test
  void testSuperClassJsonSchema() {
    String expected = "{\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"properties\":{\"sub1\":{\"type\":\"string\"},\"super1\":{\"type\":\"string\"},\"sub3\":{\"type\":\"string\"},\"super3\":{\"type\":\"string\"},\"sub2\":{\"type\":\"string\"},\"super2\":{\"type\":\"string\"}}}";
    assertEquals(expected, getSchemaGenerator().generateSchema(SubClass.class));
  }

  @JsonPropertyOrder({"sub1", "super1", "sub3", "super3", "sub2", "super2"})
  class SubClass extends SuperClass {
    public String sub1;
    public String sub2;
    public String sub3;
  }

  class SuperClass {
    public String super1;
    public String super2;
    public String super3;
  }

}

```   

Fails on AssertionFailedError:

**Expected** :{"$schema":"http://json-schema.org/draft-07/schema#","type":"object","properties":{"sub1":{"type":"string"},"super1":{"type":"string"},"sub3":{"type":"string"},"super3":{"type":"string"},"sub2":{"type":"string"},"super2":{"type":"string"}}}

**Actual**      :{"$schema":"http://json-schema.org/draft-07/schema#","type":"object","properties":{"sub1":{"type":"string"},"sub3":{"type":"string"},"sub2":{"type":"string"},"super1":{"type":"string"},"super2":{"type":"string"},"super3":{"type":"string"}}}

Debugging the test run it seems to get the SubClass fields in correct order but it has two separate propertyOrderDeclaringTypes in the map holding the field order. One is the subclass type that correct for all fields (including super) and the other super class type that is completely unnecessary and break the order. 

In the super class all field index values are MAX integer. So when generating the schema it reads incorrectly the field index value from two different indexes so the values are in no way comparable. 

The sub class order should completely override the super class order and the super class order in it's entirety souls be ignored. . Super class order should only be used when the super class is the schema root entity.

**Comment by CarstenWickner** [comment]
The fix will be part of the next release.
