### ISSUE TITLE
Add Option "ENUM_FROM_TO_STRING"

### ISSUE THREAD

**Issue by Livira** [victools/jsonschema-generator#25]
Hi all,
first of all, would like to thank you for the awesome job you are doing.
It would be great to add the Option like "ENUM_FROM_TO_STRING".
Currently, the schema is generated from the enum's `name()` method and it looks like
`"enum" : ["FIRST", "SECOND", "THIRD"]`, but the actual API response could contain values from `toString()` like `["First", "Second", "Third"]`. (This is what I am experiencing right now on my current project)

It could be a separate Module like `EnumFromToStringModule` with a method looks like this or better :)

```java
private static <E extends Enum<E>> List<String> extractEnumValuesFromToString(ResolvedType enumType) {
    Object[] enumConstants = enumType.getErasedType().getEnumConstants();
    List<String> resolvedEnumValues = new ArrayList<>();
    for (Object enumConstant : enumConstants) {
        Class<?> enumClass = enumConstant.getClass();
        try {
            Method toStringMethod = enumClass.getDeclaredMethod("toString");
            String enumValue = (String) toStringMethod.invoke(enumConstant);
            resolvedEnumValues.add(enumValue);
        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
            throw new RuntimeException(e);
        }
    }
    return resolvedEnumValues;
}
```

**Comment by CarstenWickner** [comment]
Hi @Livira,

Thank you for your kind words.
The proposal looks good and relying on `toString()` for the serialisation (at least for enum values) sounds like a common approach to decouple the all-upper-case convention for constants from the values returned in a JSON.

I'll have a look later when I find the time -- till then I assume you are fine to simply configure your own workaround, or would you need assistance with that in the meantime?

**Comment by Livira** [comment]
Hi @CarstenWickner , 
yes, I've workarounded that for now, no worries,
looking forward for this new option and thank you again

**Comment by ronan-skyscanner** [comment]
Hi,
I am having the same problem with my schemas. Is there a workaround that can be used that doesn't need to be a module?
I have tried using the `withEnumResolver` configuration but the result isn't as expected.
Could you help solving this?
Thanks

**Comment by CarstenWickner** [comment]
Hi @ronan-skyscanner,

The `withEnumResolver()` configuration defines how the `“const“` and `“enum“` fields in a JSON Schema are populated. That only gets you partially there.

On top of that, you‘d have to disable the default `Option` (the one included in your `OptionPreset`) that is deciding how to handle the Java enums being encountered.

Maybe just let me take a stab at it tonight and if the change is really as straightforward as it sounds, there‘ll be a new release with an extra option in a couple hours from now.

**Comment by CarstenWickner** [comment]
Hi @Livira and @ronan-skyscanner,

I'm happy to let you know: there is a new release [v4.1.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.1.0).
This includes a new `Option.FLATTENED_ENUMS_FROM_TOSTRING`.

The new `Option` takes precedence over the related existing `Option.FLATTENED_ENUMS` (based on `name()` or `Option.SIMPLIFIED_ENUMS` (treating them as objects, but excluding some properties). I.e. you don't have to disable those existing options, that are included in the standard `OptionPreset`s, but you can simply add the new option via:
```java
SchemaGeneratorConfigBuilder.with(Option.FLATTENED_ENUMS_FROM_TOSTRING)
```

**Comment by ronan-skyscanner** [comment]
Thanks for looking into this @CarstenWickner. 
My Java enums use the @JsonValue annotation to inform Jackson which method too use for serialising the enum values. The annotation is set on a toJson() method, as opposed to using the toString method.

Is there a way to use this Jackson annotation to derive the string for the enums? It would ensure that things are kept in sync between the schema and the resulting Json, without relying on the presence of the toString method.

**Comment by Livira** [comment]
@ronan-skyscanner , this issue was initially created for the output from toString() method.
Kindly create a separate issue for the case you describe, since current issue is resolved now
@CarstenWickner , thank you so much for quick solution!
