### ISSUE TITLE
Maven Plugin Fails if no classes are found matching Glob

### ISSUE THREAD

**Issue by Emmeral** [victools/jsonschema-generator#272]
The maven plugin fails if no classes are found matching the given glob pattern.
I would prefer this to be optional, as there are scenarios, where this is not desirable.

I have a parent pom, where I defined the plugin to generate the json schemas for every class matching a certain name. I defined it here, as I want to make sure, that it is executed in every child project. However, in some of the projects (and in the parent project specifically) none of the classes matches the glob pattern. Currently this fails the entire build, as the plugin aborts.

Personally I would prefer it, if there was another mechanism to select the classes for which a schema shall be generated (for example by an annotation). But in a first step making this behavior configurable would already help.

**Comment by CarstenWickner** [comment]
Thank you for raising this and creating the PR to introduce the corresponding parameter for it.

Adding an additional filter that considers a type annotation sounds like a nice addition as well.
Feel free to log a separate issue for that idea. And I wouldn't mind reviewing another PR. 😉
