### ISSUE TITLE
Redundant definition splitting and unwanted inlining in self-referencing type hierarchies

### ISSUE THREAD

**Issue by meztihn** [victools/jsonschema-generator#280]
### Types

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonSubTypes({
    @JsonSubTypes.Type(value = OrCondition.class, name = "or"),
    @JsonSubTypes.Type(value = EqualsCondition.class, name = "equals")
})
public sealed interface SearchCondition permits OrCondition, EqualsCondition {}

public record OrCondition(List<SearchCondition> conditions) implements SearchCondition {}

public record EqualsCondition(Object value) implements SearchCondition {}
```

### Config

```java
var config = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
    .with(new JacksonModule())
    .build();
var jsonSchema = new SchemaGenerator(config).generateSchema(SearchCondition.class);

System.out.println(jsonSchema.toPrettyString());
```

## Problems
- definitions are split in two parts (though technically correct, it's pretty confusing to read);
- base class definition is inlined (again, it's correct, but not optimal);
- there's no way to avoid definition splitting with current api (`SchemaGenerationContext#createStandardDefinitionReference` is the culprit, but the only available alternative - `SchemaGenerationContext#createStandardDefinition` - understandably leads to infinite recursion).

Using a custom definition provider, I was able to avoid base class definition inlining, but not the definition splitting.

## Possible solutions
- simple: make `SchemaGenerationContextImpl#traverseGenericType` (or it's overload) `public` - this will allow to cache definition `ObjectNode` without falling into infinite recursion;
- proper: incorporate definition reference caching into library itself by adding something like `SchemaGenerationContext#getOrCreateStandardDefinitionReference`.

### Generated
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$defs": {
        "EqualsCondition-1": {
            "type": "object",
            "properties": {
                "value": {}
            }
        },
        "EqualsCondition-2": {
            "$ref": "#/$defs/EqualsCondition-1",
            "type": "object",
            "properties": {
                "@type": {
                    "const": "equals"
                }
            },
            "required": [
                "@type"
            ]
        },
        "OrCondition-1": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "$ref": "#/$defs/OrCondition-2"
                            },
                            {
                                "$ref": "#/$defs/EqualsCondition-2"
                            }
                        ]
                    }
                }
            }
        },
        "OrCondition-2": {
            "$ref": "#/$defs/OrCondition-1",
            "type": "object",
            "properties": {
                "@type": {
                    "const": "or"
                }
            },
            "required": [
                "@type"
            ]
        }
    },
    "anyOf": [
        {
            "$ref": "#/$defs/OrCondition-2"
        },
        {
            "$ref": "#/$defs/EqualsCondition-2"
        }
    ]
}
```

### Ideal

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$defs": {
        "SearchCondition": {
            "oneOf": [
                {
                    "$ref": "#/$defs/EqualsCondition"
                },
                {
                    "$ref": "#/$defs/OrCondition"
                }
            ]
        },
        "EqualsCondition": {
            "type": "object",
            "properties": {
                "@type": {
                    "const": "equals"
                },
                "value": {}
            },
            "required": [
                "@type",
                "value"
            ]
        },
        "OrCondition": {
            "type": "object",
            "properties": {
                "@type": {
                    "const": "or"
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/SearchCondition"
                    }
                }
            },
            "required": [
                "@type",
                "conditions"
            ]
        }
    },
    "$ref": "#/$defs/SearchCondition"
}
```

**Comment by CarstenWickner** [comment]
Hi @meztihn,

Thanks for raising this  – especially in such a structured way.
This was brought up before, but I wasn't yet able to properly investigate where it goes wrong.

As a matter of fact, your second proposal "incorporate definition reference caching into the library" is already in place. Still, for some reason, this secondary (internal) definition ends up in the `$defs` although it should be detected as occurring just once and thereby get automatically inlined.

-----

In regards to your "Ideal" result:
- Putting the main schema into the `$defs` can be achieved via the `Option.DEFINITION_FOR_MAIN_SCHEMA`.
- Including the `value`/`conditions` properties in the `"required"` array is just [a matter of configuration](https://victools.github.io/jsonschema-generator/#quot-required-quot-keyword).
- Using `oneOf` always feels a bit strong to me, as a schema validator then has to check all subschemas to ensure precisely one matches. Whereas using `anyOf` with distinct subschemas (e.g., via the `type` property) allows the schema validator to stop after the first match was found. If the subschemas are not distinct syntactically, `oneOf` might result in something being rejected as ambiguous, while `anyOf` would be more lenient and not necessarily care which subschema was the appropriate choice. The parser may still apply some meaningful default behavior then. If you disagree, we could probably just make it configurable whether `oneOf` or `anyOf` should be used for these subtype definitions.
- I fully agree that combining both definitions looks nicer in the schema as such. It just means some redundancy if the "original" `-1` definition (without the subtype identifier) were to be included directly as well. But in most cases, that is probably not happening anyway, i.e., that might be acceptable on those few rare occasions. Still need to check whether the remaining (now `-2`) definition ensures that there is no endless loop even in the case of circular references.

**Comment by meztihn** [comment]
@CarstenWickner thanks for the swift answer. Can you, please, point out where this caching is in the code? I haven't noticed it while looking into the code.

- Sadly, `Option.DEFINITION_FOR_MAIN_SCHEMA` (as well, as `Option.DEFINITIONS_FOR_ALL_OBJECTS`) doesn't help when `SearchCondition` is not the target class, e.g. `record SomeRequest(SearchCondition condition) {}` gives this schema (dropped `$defs` and such for clarity):
```json
{
  "type" : "object",
  "properties" : {
    "condition" : {
      "anyOf" : [ {
        "$ref" : "#/$defs/OrCondition-2"
      }, {
        "$ref" : "#/$defs/EqualsCondition-2"
      } ]
    }
  }
}
```
- Yeah, it's not related to this issue. It's included just for the sake of completeness.
- I haven't researched validation nuances in this case, so maybe it is a better solution. It's just makes sense to me that a json has to conform to one of these definitions, but not to the union of some of them, since we're talking about a representation of Java classes and not of Typescript for example.
- Yeah, I can imagine a case when it is needed separately - in a convoluted type hierarchy, - but that's rare. I hope. Can we check whether is it (could be) used separately and inline if not, since we want correctness in all cases?
I guess you're talking about this case, where we can't use `FirstLevel` class definition with `@type` property when referencing it from `SecondLevel` definition.
```java
@JsonSubTypes({
    @JsonSubTypes.Type(FirstLevel.class),
    @JsonSubTypes.Type(SecondLevel.class),
})
interface Base {}

class FirstLevel {}

class SecondLevel extends FirstLevel {}
```

**Comment by CarstenWickner** [comment]
> Can you, please, point out where this caching is in the code?

1. While iterating over the various types included in the schema being generated, the `SchemaGenerationContextImpl` class collects both the "definitions" of subschemas and the placeholder "references" (i.e., empty `ObjectNode` instances) during the process.
https://github.com/victools/jsonschema-generator/blob/3712300eb42e6df229c8a0b3201e2f48e9e616be/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java#L64-L66
2. Only at the very end of the process, are the "definitions" either put into the `$defs` and a `$ref` is added to each "reference", or (at least per standard behavior) in the case of just a single "reference" having been recorded, that "reference" is being filled with a copy of the respective "definition".
https://github.com/victools/jsonschema-generator/blob/3712300eb42e6df229c8a0b3201e2f48e9e616be/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java#L123

> Sadly, `Option.DEFINITION_FOR_MAIN_SCHEMA` (as well, as `Option.DEFINITIONS_FOR_ALL_OBJECTS`) doesn't help when `SearchCondition` is not the target class.

Yes, I guess that would require a small change in the way the subtype resolution is currently handled. I'm open to a pull request. 😉
Probably around here:
https://github.com/victools/jsonschema-generator/blob/3712300eb42e6df229c8a0b3201e2f48e9e616be/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java#L329

> It just makes sense to me that a json has to conform to one of these definitions, but not to the union of some of them, since we're talking about a representation of Java classes and not of Typescript for example.

That is a valid point and I'm merely concerned about the scenario where the differences between Java classes might just be a differing implementation of methods while the contained fields are identical. In the absence of an identifier like the `@type` property, there may be no way to differentiate them based on the JSON alone. I just prefer avoiding issues in such edge cases. That being said: I'm fully onboard regarding `oneOf` being a better representation of the semantics/meaning than `anyOf`. Again, if the subschemas are distinct, `oneOf` and `anyOf` would produce the same results. `anyOf` might just allow the validator to take some shortcuts.

> Can we check whether it (could be) used separately and inline if not, since we want correctness in all cases?

Yes, during the schema generation process, I'm including a couple of ´allOf` wrappers where they are technically not required, just to keep the code simple.
At the end of the process, I'm then doing the "clean-up" and try to get rid of obsolete `allOf`/`anyOf`/`oneOf` lists in order to make the resulting schema simpler. Combining these definitions would require a bit more "aggressive" consolidation of subschemas, but I wanted to do that for quite a while – just hardly finding the time to properly focus on it. Basically, we'd have to extend the list of schema properties, that are assumed to be fine to merge.
https://github.com/victools/jsonschema-generator/blob/3738e9a9cf43160014e2ffbbbfa21f657cbd9f3f/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java#L160
The first step however might be to fix the fact that in your example there is a single `$ref` for the `-1` definitions, when they actually should be inlined (as per my answer to the first point here). Once that `-1` definition is inlined, the "clean-up" has an easier job without having to resolve the referenced subschema first.

**Comment by CarstenWickner** [comment]
HI @meztihn,

I've been working on this a bit. And [this test class](https://github.com/victools/jsonschema-generator/blob/main/jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionSimpleIntegrationTest.java) illustrates the current/improved behavior, which produces a schema with explicit definitions both for a supertype and its subtypes:
```json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$defs": {
        "TestSubClassA": {
            "allOf": [{
                    "type": "object",
                    "properties": {
                        "aProperty": {
                            "type": "string"
                        }
                    }
                }, {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "const": "SubClassA"
                        }
                    },
                    "required": ["@type"]
                }]
        },
        "TestSubClassB": {
            "allOf": [{
                    "type": "object",
                    "properties": {
                        "bProperty": {
                            "type": "integer"
                        }
                    }
                }, {
                    "type": "object",
                    "properties": {
                        "@type": {
                            "const": "SubClassB"
                        }
                    },
                    "required": ["@type"]
                }]
        },
        "TestSuperClass": {
            "anyOf": [{
                    "$ref": "#/$defs/TestSubClassA"
                }, {
                    "$ref": "#/$defs/TestSubClassB"
                }]
        }
    },
    "type": "object",
    "properties": {
        "supertypeA": {
            "$ref": "#/$defs/TestSuperClass",
            "description": "A member description"
        },
        "supertypeB": {
            "$ref": "#/$defs/TestSuperClass"
        }
    }
}
```

This is being achieved via this configuration:
```java
SchemaGeneratorConfig config = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON)
        .with(Option.DEFINITIONS_FOR_MEMBER_SUPERTYPES)
        .with(new JacksonModule(JacksonOption.ALWAYS_REF_SUBTYPES))
        .build();
```
- The `Option.DEFINITIONS_FOR_MEMBER_SUPERTYPES` is new and needs to be used with care, as it reduces the information available to the subtype schemas (which is the reason, that was previously not possible). In fact, enabling this may result in an invalid schema being generated, e.g., if per-property overrides of the jackson subtype handling is present.
While jackson explicitly supports this (as well as this schema generation library) it may not be very common. In projects, where there is only a single subtype handling defined on a given supertype, which is globally applied, this `Option` should be acceptable to use.
- The `JacksonOption.ALWAYS_REF_SUBTYPES` is also new and makes use of yet another new standard feature, that each `CustomDefinition` can now explicitly state whether it should end up in the `$defs` block. Previously, it was only possible to say: always `INLINE` or apply the `STANDARD` behavior (i.e., move into `$defs` if referenced at least twice). Now the custom definition can also indicate to `ALWAYS_REF`, i.e., always be referenced even just from a single place.

I did also look into consolidating the subtype schema's `allOf` array, but that is quite involved and I don't have the time/capacity to see this through at the moment.
I hope this is good enough for now.
