### ISSUE TITLE
How do i use the jsonschema-generator for interfaces?

### ISSUE THREAD

**Issue by gzahl** [victools/jsonschema-generator#284]
I want to generate schema for my interface classes, e.g.

```java
public interface MyDto {

    @JsonPropertyDescription("Filename")
    @NotBlank String getFileName();

    @JsonPropertyDescription("Size of file in bytes.")
    @NotNull BigInteger getContentLength();

    @JsonPropertyDescription("Sha256 sum of file.")
    @NotBlank String getSha256sum();
}
```

These might be interfaces with or without Jackson or any validation annotations.
Can the jsonschema-generator be configured in a suitable way? It seema to always require a matching field. But i want to only let it search for the Getter-naming convention.

edit: Using JAVA_ONLY OptionPreset using a interface generally works, but the properties have not the expected property name, but the name of the getter, e.g. "getFileName()".

**Comment by CarstenWickner** [comment]
Yes, you can configure it to include parameter-less non-void methods and then let rename those to exclude the "get" prefix.
I can share an example later, once I find the time.

**Comment by gzahl** [comment]
Hi Carsten,
Thanks for the pointer. The preset JAVA_OBJECT with option FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS did work. I think i get the hang of it slowly. Quite a few possibilities to combine options.
Thanks for the library and the support, looking forward to OpenAPI support!

**Comment by CarstenWickner** [comment]
HI @gzahl,

I'm glad it helped.
Regarding OpenAPI, that has a somewhat different scope and I guess using the swagger libraries is a good way to generate these kinds of API descriptions. No need to re-do all that. I'm just focussing on the JSON schema side of things here.

That being said, there are two additional `Option` values to get the JSON schema produced here closer to what OpenAPI expects of its contained JSON schema parts:
- `Option.EXTRA_OPEN_API_FORMAT_VALUES`
- `Option.PLAIN_DEFINITION_KEYS`

Doesn't look like I will get much further than that on my own any time soon.
Always appreciating pull requests though. 😉
