### ISSUE TITLE
Support for 'deprecated'

### ISSUE THREAD

**Issue by mduft** [victools/jsonschema-generator#288]
It would be nice to have support for the 'deprecated' meta-data annotation (https://json-schema.org/draft/2020-12/json-schema-validation.html#section-9.3)

We have DTOs like so in Java:

```
    @JsonAlias("uid")
    @JsonPropertyDescription("The ID of the parameter. This ID must be unique in a given application.")
    public String id;

    // Compat with 4.x
    @Deprecated(forRemoval = true)
    @JsonProperty("uid")
    @JsonPropertyDescription("DEPRECATED: Use 'id' instead.")
    public String getUid() {
        return id;
    };
```

The whole construct to allow the usage of 'uid' in existing data, whilst using the new 'id' whenever writing (and internally when using).

**Comment by CarstenWickner** [comment]
Hi @mduft,

You can achieve this through configuration already. E.g., via [Instance Attribute Overrides](https://victools.github.io/jsonschema-generator/#instance-attribute-overrides).
```java
configBuilder.forMethods().withInstanceAttributeOverride((node, method, context) -> {
    if (method.getAnnotation(Deprecated.class) != null) {
        node.put("deprecated", true);
    }
});
```
I`m assuming you are including `Option.NONSTATIC_NONVOID_NONGETTER_METHODS` as well as `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS` and explicitly ignore methods that have parameters then.

**Comment by mduft** [comment]
Thanks a ton :) That looks nice. I'm using

```
JacksonModule jm = new JacksonModule(JacksonOption.RESPECT_JSONPROPERTY_REQUIRED,
                JacksonOption.INCLUDE_ONLY_JSONPROPERTY_ANNOTATED_METHODS);

SchemaGeneratorConfigBuilder cfgBuilder = new SchemaGeneratorConfigBuilder(JacksonHelper.createDefaultObjectMapper(),
                SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON).with(jm);

        // include all methods which are there for compatibility mapping of properties. jackson module filters only those with annotation.
        cfgBuilder.with(Option.NONSTATIC_NONVOID_NONGETTER_METHODS, Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS);
```

So far that works as I expected it, and only `@JsonProperty` annotated methods are included, which are (in my case) always such backwards compatibility methods.

Will try this today.

**Comment by mduft** [comment]
Tried it, and (surprise) works like a charm :) Thanks!
