### ISSUE TITLE
Releasing unreleased features

### ISSUE THREAD

**Issue by Emmeral** [victools/jsonschema-generator#290]
Is there any release plan/data for the now unreleased features?
As I need to use them in production code, I would prefer not to depend on the current snapshot build.

**Comment by CarstenWickner** [comment]
As you wish: release [v4.27.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.27.0) has been published.

To answer your question more in general: I usually just collect changes until they seem "big enough" to justify a release or until someone asks for it. 😉
