### ISSUE TITLE
Kotlin getter should become a field in the schema

### ISSUE THREAD

**Issue by tokazio** [victools/jsonschema-generator#292]
When i want to generate a schema for a data class having

`override val endUser: Boolean
        get() = userId != null`

i want to have endUser as a field in the schema

`"endUser" : {
      "type" : "boolean"
    }`

**Comment by CarstenWickner** [comment]
Hi @tokazio,

Are these two options not working for you?
- `Option. NONSTATIC_NONVOID_NONGETTER_METHODS`
- `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS`

You may need to exclude methods with arguments explicitly then, if you have some that aren't `void`.

**Comment by tokazio** [comment]
ah nice it works ! thank you
