### ISSUE TITLE
Option.EXTRA_OPEN_API_FORMAT_VALUES generates invalid JSON schemas

### ISSUE THREAD

**Issue by albrechtflo-hg** [victools/jsonschema-generator#302]
## Bug description

When using this option, numeric fields (e.g. `integer`) receive a `format` field with e.g. `int32` as its format. This is illegal according to the [JSON Schema Spec](https://json-schema.org/understanding-json-schema/reference/numeric.html) and leads to invalid schemas.

Most parsers accept this, but their behaviour in this case is not strictly defined. For example, https://github.com/everit-org/json-schema interprets this as `"allOf": [ {"type":"integer"}, {} ]` - due to the presence of the `format` property, an empty `StringSchema` is constructed, which does luckily not explicitly require the value to be String (as not defined by a `type` property).

There should be an option to only apply the format values for string-based properties (IMO, this should be the default when using this option, as everything else generates invalid schemas).

## Code for reproduction

JsonSchemaGeneratorTest.java:
```java
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.github.victools.jsonschema.generator.*;

public class JsonSchemaGeneratorTest {

    public static void main(String[] args) {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        objectMapper.registerModule(new JavaTimeModule());
        SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON);

        SchemaGeneratorConfig config = configBuilder.with(Option.ADDITIONAL_FIXED_TYPES,
                        Option.EXTRA_OPEN_API_FORMAT_VALUES).build();
        SchemaGenerator generator = new SchemaGenerator(config);

        JsonNode jsonSchema = generator.generateSchema(MyType.class);
        System.out.println(jsonSchema.toPrettyString());
    }

}
```

MyType.java:

```java
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
public class MyType {

    private Integer intField;
    private String stringField;
    private LocalDateTime dateField;

}
```

Output:

```json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "type" : "object",
  "properties" : {
    "dateField" : {
      "type" : "string",
      "format" : "date-time"
    },
    "intField" : {
      "type" : "integer",
      "format" : "int32"
    },
    "stringField" : {
      "type" : "string"
    }
  }
}
```

## Workaround

Here is a simple, incomplete, workaround:

```java
TypeAttributeOverrideV2 removeFormatFromNumerics = (node, scope, context) -> {
    Class<?> fieldType = scope.getType().getErasedType();
    if (fieldType == int.class || fieldType == long.class || Number.class.isAssignableFrom(fieldType)) {
        node.remove("format");
    }
};
configBuilder.forTypesInGeneral().withTypeAttributeOverride(removeFormatFromNumerics);
```

**Comment by CarstenWickner** [comment]
Hi @albrechtflo-hg,

Thanks for raising this in such detail.

However, the `Option.EXTRA_OPEN_API_FORMAT_VALUES` suggests that it is meant for usage in the context of OpenAPI, not strictly JSON Schema.
-  The implementation is according to the OpenAPI documentation: https://swagger.io/docs/specification/data-models/data-types/#numbers
- If you don't want to use the generated schema in the context of OpenAPI but as a "normal" JSON Schema, I suggest you omit that option.

Additionally, I'm afraid I have to disagree with the `format` keyword being "illegal" in a JSON Schema.
The documentation suggests that it is mainly intended for `string` values – yes, but it's mostly an indication and not necessarily meant for validation. It's certainly not implying a `string` value being allowed.
https://json-schema.org/understanding-json-schema/reference/string.html?highlight=format#format

I'd therefore not deem this a bug in the schema generation here. Instead, it appears to be a bug in the schema validation library, that over-interprets the `format` keyword.

That being said, I understand that this OpenAPI aspect may be confusing in the context of this JSON schema generation library. The safer option would be to remove the `Option` then or remove that part of the implementation, but it feels like working around a bug in the schema validation library.
