### ISSUE TITLE
Use Kotlin null-safety to determine required fields when using NOT_NULLABLE_FIELD_IS_REQUIRED

### ISSUE THREAD

**Issue by marceloverdijk** [victools/jsonschema-generator#304]
When using Kotlin like:

```
val jakartaValidationModule = JakartaValidationModule(JakartaValidationOption.NOT_NULLABLE_FIELD_IS_REQUIRED)
val configBuilder = SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
            .with(jacksonModule)
            .with(jakartaValidationModule)
val generator = SchemaGenerator(configBuilder.build())
val jsonSchema = generator.generateSchema(Country::class.java)
val jsonSchemaAsString = jsonSchema.toPrettyString()
```

with:

```
class Country {

    var alpha2Code: String = ""
    var name: String = ""
    var demonym: String? = null
}
```

the `alpha2Code` and `name` properties should be part of the required properties in the json schema.
This as they are already set as required by the Kotlin syntax; note see that `demonym` is not required by the `?`.

I assume this is not so easy and it probably requires a specific Kotlin module...

Current workaround is to do:

```
class Country {

    @NotNull
    var alpha2Code: String = ""

    @NotNull
    var name: String = ""

    var demonym: String? = null
}
```

but actually I'm specifying it twice now...

**Comment by CarstenWickner** [comment]
Hi @marceloverdijk,

I get where you're coming from and fully agree with the added convenience this would offer.
Similar to reading the information from the JavaDoc/KDoc, I'm afraid this question mark is not something one could access from the compiled classes, is it?

**Comment by marceloverdijk** [comment]
You are right. I was a bit to enthusiastic ;-)
Let's close this.

**Comment by moranlefler** [comment]
Actually, you can achieve something like this if you configure the schema generator from Kotlin:

```kotlin

// wherever you configure the generator...
 configBuilder
        .forFields().withRequiredCheck {
          !isNullable(kClass, it)
        }

private fun isNullable(type: KClass<*>, it: FieldScope): Boolean {
    val properties = type.declaredMemberProperties
    for (property in properties) {
      if (property.name == it.name) {
        return property.returnType.isMarkedNullable
      }
    }
    return false
  }
```

This example is rather simplistic and will only work for top-level fields, but it can be improved by implementing the Kotlin equivalent of `FieldScope` and tracing the appropriate KType from the member scope.

**Comment by tomasAlabes** [comment]
@moranlefler were you able to implement this logic in a more generic way?
