### ISSUE TITLE
[Q] Best way to define root id, title, description values

### ISSUE THREAD

**Issue by marceloverdijk** [victools/jsonschema-generator#307]
I would like to set "hardcoded" id, title and description values of the **root** of the generated schema's.

I used something like:

```
configBuilder
            .forTypesInGeneral()
            .withIdResolver { scope -> if (scope.type.erasedType == mainTargetType)"my-id" else null }
            .withTitleResolver { scope -> if (scope.type.erasedType == mainTargetType) "my-title" else null }
            .withDescriptionResolver { scope -> if (scope.type.erasedType == mainTargetType) "my-description" else null }
```

which works.

I'm one wondering if this is the best way to do this?

E.g.

```
JsonNode jsonSchema = generator.generateSchema(List.class, Country.class);
```

then the mainTargetType is `List` and I'm concerned this can bite me later when using a List somewhere else...

Next to that I noticed that when generating the schema it generates it like:

```
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    ..
  },
  "type" : "array",
  "items" : {
    "$ref" : "#/$defs/Country"
  },
  "$id" : "my-id",
  "title" : "my-title",
  "description" : "my-description"
}
```

for readability, it would be nice to have to id, title and description properties more at the top like (and also $defs at the botton):

```
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
 "$id" : "my-id",
  "title" : "my-title",
  "description" : "my-description",
  "type" : "array",
  "items" : {
    "$ref" : "#/$defs/Country"
  },
  "$defs" : {
    ..
  }
}
```

is this order possible to manipulate? No big deal if not possible.

**Comment by CarstenWickner** [comment]
Hi @marceloverdijk,

These are two separate questions.

### How to best set "hardcoded" `id`, `title` and `description` values of the root of the generated schema?
I'd not bother doing this through configuration on the schema generator itself.
The produced schema is returned as a jackson `ObjectNode`. You can add those root-level properties directly, without even having to hard-code the technical attribute names.
```java
SchemaGeneratorConfig config = configBuilder.build();
SchemaGenerator generator = new SchemaGenerator(config);
ObjectNode jsonSchema = generator.generateSchema(List.class, Country.class);
// add root-level attributes
jsonSchema.put(config.getKeyword(SchemaKeyword.TAG_ID), "my-id");
jsonSchema.put(config.getKeyword(SchemaKeyword.TAG_TITLE), "my-title");
jsonSchema.put(config.getKeyword(SchemaKeyword.TAG_DESCRIPTION), "my-description");
```

### How to sort the keywords/attributes inside a schema in a more meaningful way?
There is no specific configuration for this available out-of-the-box.
However, it depends on which parts of the schema you intend to sort.
- If you want to sort the attributes in all sub-schemas, you could make use of the fact that "InstanceAttributeOverrides" and "TypeAttributeOverrides" are designed to be invoked as the very last thing for each field/method/type, i.e., you'd then "only" have also to consider nested elements in `allOf`/`anyOf`/`oneOf` etc.
- If you want to sort the attributes only on the root schema, then again I'd suggest doing this on the returned `ObjectNode` directly, e.g.
```java
ObjectNode jsonSchema = generator.generateSchema(List.class, Country.class);
// add root-level attributes
jsonSchema.put(config.getKeyword(SchemaKeyword.TAG_ID), "my-id");
jsonSchema.put(config.getKeyword(SchemaKeyword.TAG_TITLE), "my-title");
jsonSchema.put(config.getKeyword(SchemaKeyword.TAG_DESCRIPTION), "my-description");
// collect all fields/attributes
Stream.Builder<Map.Entry<String, JsonNode>> fieldStreamBuilder = Stream.builder();
jsonSchema.fields().forEachRemaining(fieldStreamBuilder::add);
// remove them from the generated schema
jsonSchema.removeAll();
// add them again in the desired order (preserving the original order of all unspecified attributes)
fieldStreamBuilder.build()
        .sorted(Comparator.comparingInt(field -> getSortOrderForSchemaAttribute(field.getKey())))
        .forEachOrdered(field -> jsonSchema.set(field.getKey(), field.getValue()));
```
The desired order could be defined via something like this:
```java
private static int getSortOrderForSchemaAttribute(String attributeName) {
    switch (attributeName) {
    case "$schema":
        return 1;
    case "$id":
        return 2;
    case "title":
        return 3;
    case "description":
        return 4;
    case "$defs":
        return 100;
    default:
        // all others before "$defs" in their default order
        return 99;
    }
}
```

**Comment by marceloverdijk** [comment]
Thx a lot. This is really helpful!!
