### ISSUE TITLE
Adding @Schema on an enum field and on the enum generates an allOf 

### ISSUE THREAD

**Issue by loicmathieu** [victools/jsonschema-generator#311]
Hi,

When using `@Schema` on both a class attribute and the Enum, a schema with `allOf` is generated. 
This seems like a bug to me as `allOf` means there is multiple different typse but here there is one type, the enum.
When adding `@Schema` only in the attribute or only in the Enum everything is OK.

This class:

```java
@Getter
private static class TaskWithEnum extends Task implements RunnableTask<VoidOutput>  {

        @PluginProperty
        @Schema(title = "Title from the attribute")
        private TestEnum testEnum;

        @Schema(title = "Title from the enum")
        private enum TestEnum {
            VALUE1, VALUE2, VALUE3
        }
}
```

Generates the following schema:

```
$defs={}, properties={testEnum={allOf=[{type=string, enum=[VALUE1, VALUE2, VALUE3], title=Title from the enum}, {title=Title from the attribute}]}}}
```

**Comment by CarstenWickner** [comment]
Hi @loicmathieu,

This is not a bug, but a feature. 😉

`allOf` just means that all sub-schemas have to be fulfilled at the same time.

https://json-schema.org/understanding-json-schema/reference/combining.html#allof

**Comment by loicmathieu** [comment]
Hi, I fear you'll answer that ;)

Here I found it's an edge case as the schema at the declaration site didn't bring any "schema constraint" like type or value constraint but only descriptive information. So allOf is kind of strange but I understant the rational.
