### ISSUE TITLE
Support Java Modules

### ISSUE THREAD

**Issue by aalmiray** [victools/jsonschema-generator#313]
I'd be great if the library supplied a full Java module descriptor. It's possible to keep bytecode baseline compatible with Java 8 while providing a full module descriptor thanks to [ModiTect](https://github.com/moditect/moditect). If interested I can send a PR to make it happen.

**Comment by CarstenWickner** [comment]
Hi @aalmiray 

A PR would be appreciated.
Looking forward to it.

**Comment by CarstenWickner** [comment]
Thanks @aalmiray.
Your PR has been merged.

**Comment by CarstenWickner** [comment]
This has been used in the latest release [v4.29.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.29.0) for the first time now.

Thanks again for your contribution @aalmiray.

**Comment by aalmiray** [comment]
My pleasure 😅
