### ISSUE TITLE
bug in SchemaCleanUpUtils::returnOverlapOfStringsOrStringArrays

### ISSUE THREAD

**Issue by amirhadadi** [victools/jsonschema-generator#348]
In version 4.31.0 there's [this call](https://github.com/victools/jsonschema-generator/blob/f93681b98b8029410133fc521842cfe54860955f/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java#L389).
This requires `encounteredValues` to be mutable, but it's not due to [the use of `Collections.singletonList`](https://github.com/victools/jsonschema-generator/blob/f93681b98b8029410133fc521842cfe54860955f/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java#L412).

As a result we see this exception:

```
java.lang.UnsupportedOperationException: null
    at java.util.Collections$1.remove(Collections.java:4787) ~[?:?]
    at java.util.AbstractCollection.retainAll(AbstractCollection.java:404) ~[?:?]
    at com.github.victools.jsonschema.generator.impl.SchemaCleanUpUtils.returnOverlapOfStringsOrStringArrays(SchemaCleanUpUtils.java:389) ~[jsonschema-generator-4.31.0.jar:?]
```

**Comment by amirhadadi** [comment]
@CarstenWickner thanks for the quick fix.
[Here's](https://gist.github.com/amirhadadi/88ca4f31f9f9d8327d0c06da5806c031) a failing schema.
The failure is due to the repeating `"type": "object"` of the 2 top level elements.

**Comment by CarstenWickner** [comment]
Hi @amirhadadi,

Two times `"type": "object"` would not have triggered this error.
Only the invalid schema of the `name` property does:
```json

{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "name": {
          "allOf": [
            {
              "type": "string"
            },
            {
              "type": "object",
              "properties": {
                "type": {
                  "const": "String"
                }
              },
              "required": [
                "type"
              ]
            }
          ]
        }
      }
    }
  ]
}
```
I strongly suggest you double-check your generator configuration why this `"String"` type is being added there. It looks like it is treated as a subtype definition.
