### ISSUE TITLE
root level description issue

### ISSUE THREAD

**Issue by patpatpat123** [victools/jsonschema-generator#350]
Hello team,

I am currently facing an issue and wanted to reach out.

What I am trying to achieve:

I would like the schema to contain a root level ```description```, like this

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Some very important root level description",
  "definitions": {
[...]
}
```

Just to avoid confusion, it is not the description of a field, nor the description of a method etc, but the description of the json.

I tried using ```.withDescriptionResolver``` but it seems it is only generating for fields and methods.

May I ask how to achieve the ```description``` at root level please?

Thank you

**Comment by CarstenWickner** [comment]
Hi @patpatpat123,

If you use `configBuilder.forTypesInGeneral().withDescriptionResolver()` you should be able to target the main type for which the schema is being generated.
Alternatively, you can simply add the `"description"` property to the `ObjectNode` containing the full schema (if you're not going through the Maven plugin).

**Comment by patpatpat123** [comment]
This is indeed correct, this project covers a lot of things. Many thanks
