### ISSUE TITLE
Option to extract annotations of the class

### ISSUE THREAD

**Issue by saamrezaei** [victools/jsonschema-generator#354]
Hello,

I'm trying to include the collection of annotations attached to my java classes. However, it seems there is no Option that enables this. Am I missing something, or is this currently not a functionality?

**Comment by CarstenWickner** [comment]
Hi @saamrezaei,

I'm afraid I don't understand exactly what you're after.

Can you perhaps provide an example class and the corresponding JSON schema you want to produce for it?

**Comment by saamrezaei** [comment]
I was able to achieve what I was looking for using this code. 

I attached this resolver to my SchemaGeneratorConfigBuilder:
`builder.forTypesInGeneral().withDefaultResolver(SchemaGeneratorFactory::classAnnotation);
`
The classAnnotation method looks like this:
```
  private static String classAnnotation(TypeScope typeScope) {
    return Stream.of(typeScope.getType().getErasedType().getAnnotations()).filter(a -> a.annotationType().equals(MyCustomAnnotation.class)).findFirst().map(Annotation::toString).orElseThrow(RuntimeException::new);
  }
```

**Comment by saamrezaei** [comment]
Basically, I was trying to include the annotations attached to the class itself inside the generated json schema. Not the annotations attached to individual fields. 

So if my class looked like this: 
```
@MyCustomAnnotation({"extra context about class"})
public class MyClass {
  private int temp;
}
```
My json schema would include a section specifying the annotations of the class along with the extra context provided from that annotation

**Comment by CarstenWickner** [comment]
HI @saamrezaei,

The overall approach looks good. Just two notes:
- You probably want to use the `withDescriptionResolver()` rather than the `withDefaultResolver()` for such additional context information.
- Maybe also, don't be so harsh about a missing annotation. Throwing a `RuntimeException` for any type missing that annotation is likely to fall on your feet unless that is really a hard requirement in your whole data model.

Perhaps something like:
```java
builder.forTypesInGeneral().withDescriptionResolver(
        scope -> Optional.ofNullable(scope.getErasedType().getAnnotation(MyCustomAnnotation.class))
                .map(MyCustomAnnotation::value).orElse(null)
); 
```
