### ISSUE TITLE
Support for @JsonUnwrapped in the Jackson module

### ISSUE THREAD

**Issue by moranlefler** [victools/jsonschema-generator#357]
I have a class definition like this (Kotlin):
```kt
data class EventClass<T>(
    @JsonUnwrapped
    val commonEventData: CommonEventData,
    @JsonUnwrapped
    val eventBaselineClass: T,
)

data class CommonEventData(
    @JsonProperty("event_id")
    val eventId: String,
)
```

I'd like to generate schemas for event classes of different types and embed the common data in the same level as the baseline class.
When deserializing such cases, the `event_id` attribute is created under the root node, so I expect the attribute key to appear under the root `properties` node in the schema.

The schema that is generated with the current version of `jsonschema-generator` is:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "commonEventData": {
      "type": "object",
      "properties": {
        "eventId": {
          "type": "string"
        }
      }
    },
    "eventBaselineClass": {
      "type": "object",
      "properties": {
        "number": {
          "type": "integer"
        }
      }
    }
  }
}
```

Instead of the expected schema:

```json
{
  "$schema":"https://json-schema.org/draft/2020-12/schema",
  "type":"object",
  "properties":{
    "eventId":{
      "type":"string"
    },
    "number":{
      "type": "integer"
    }
  }
}
```

Is there an existing configuration that would allow me to achieve this or is this feature just not supported?

**Comment by CarstenWickner** [comment]
Hi @moranlefler,

In short: the `@JsonUnwrapped` annotation is not yet supported out of the box.

For now, you'd have to handle this through advanced configuration yourself.

When I find the time, I'll also look into "proper" support then. I have some ideas already. 😃

**Comment by CarstenWickner** [comment]
As per PR #362, basic support of the jackson `@JsonUnwrapped` will be added in the next release (4.32.0).

**Comment by CarstenWickner** [comment]
Release [v4.32.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.32.0) has been published, including this change.
