### ISSUE TITLE
NoSuchMethodError with 4.4.0

### ISSUE THREAD

**Issue by skohlmann** [victools/jsonschema-generator#36]
Following error occurs while using 4.4.0:

`java.lang.NoSuchMethodError: com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder.forTypesInGeneral()Lcom/github/victools/jsonschema/generator/SchemaGeneratorTypeConfigPart;`

Problem doesn't occur with 4.3.0.

Environment: 
- Java 11

Code:
```java
public void createSchema(final Class clazz, final Writer target) throws IOException {
    final ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.writerWithDefaultPrettyPrinter();
    final var configBuilder = new SchemaGeneratorConfigBuilder(objectMapper, OptionPreset.PLAIN_JSON);
    final var config = configBuilder.with(Option.NONPUBLIC_NONSTATIC_FIELDS_WITHOUT_GETTERS)
                                    .with(new JacksonModule())
                                    .with(new JavaxValidationModule(INCLUDE_PATTERN_EXPRESSIONS, NOT_NULLABLE_FIELD_IS_REQUIRED))
                                    .build();
    final var generator = new com.github.victools.jsonschema.generator.SchemaGenerator(config);
    final var jsonSchema = generator.generateSchema(clazz);

    target.write(jsonSchema.toPrettyString());
    target.flush();
}
```

Maven dependency:
```xml
<dependency>
    <groupId>com.github.victools</groupId>
    <artifactId>jsonschema-generator</artifactId>
    <version>[4.0.0,5.0.0)</version>
</dependency>
<dependency>
    <groupId>com.github.victools</groupId>
    <artifactId>jsonschema-module-javax-validation</artifactId>
    <version>[4.0.0,5.0.0)</version>
</dependency>
<dependency>
    <groupId>com.github.victools</groupId>
    <artifactId>jsonschema-module-jackson</artifactId>
    <version>[4.0.0,5.0.0)</version>
</dependency>
```
FasterXML Jackson is 2.10.2.

**Comment by CarstenWickner** [comment]
Hi @skohlmann,

Thanks for reporting this!
`SchemaGeneratorConfigBuilder.forTypesInGeneral()` now returns a subtype of `SchemaGeneratorTypeConfigPart`.
Sounds like I need to re-release the modules. Strange, but at least not a big task.

**Comment by CarstenWickner** [comment]
Hi @skohlmann,

I've re-released the three standard modules now.
For simplicity's sake also as version 4.4.0 to match the main `jsonschema-generator` version.

I'm not even sure if it is just because of JDK 11 being stricter than older versions or whether they would have a complained.

Nevertheless, it should be fine now.
Thanks again for reporting!

**Comment by skohlmann** [comment]
Checked again with our production environment. Solution works fine. Changed dependency range from [4.0.0,4.3.0) to [4.4.0,5.0.0). 
Thx for fast problem solving.
