### ISSUE TITLE
No standard API nor Annotation to express Examples for a json-schema

### ISSUE THREAD

**Issue by ivy-rew** [victools/jsonschema-generator#360]
Hi, victools is great and I'm starting to use it in many projects. Thanks for the great work. :1st_place_medal: 

However, today I'd like to express some 'example' values on a field and couldn't find an API to contribute examples. 
https://json-schema.org/understanding-json-schema/reference/generic.html#id2

So I built one on my own: would you like to add this as core feature? Or did I just miss an already existing mechanism to contribute examples?

My rough implementation looks as follows.

Examples Annotation

```java
package ch.ivyteam.ivy.config.schema.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Documents valid example values.
 * VS-Code will use them just like classic 'enum' types: and list em as completable values.
 *
 * @see "https://json-schema.org/understanding-json-schema/reference/generic.html#id2"
 *
 */
@Target({ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Examples {

  /**
   * @return the value of a JSON schema <code>examples</code> field.
   */
  public String[] value() default "";
}
```

A provider that handles the annotation:
```java
package ch.ivyteam.ivy.config.schema;

import java.util.Arrays;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.github.victools.jsonschema.generator.CustomPropertyDefinition;
import com.github.victools.jsonschema.generator.CustomPropertyDefinitionProvider;
import com.github.victools.jsonschema.generator.FieldScope;
import com.github.victools.jsonschema.generator.SchemaGenerationContext;
import com.github.victools.jsonschema.generator.SchemaKeyword;

import ch.ivyteam.ivy.config.schema.annotations.Examples;

class ExamplesProvider implements CustomPropertyDefinitionProvider<FieldScope> {

  @Override
  public CustomPropertyDefinition provideCustomSchemaDefinition(FieldScope scope, SchemaGenerationContext context) {
    Examples examples = scope.getAnnotation(Examples.class);
    if (examples == null) {
      return null;
    }
    var def = context.createStandardDefinition(scope, this);

    JsonNode allOf = def.get(SchemaKeyword.TAG_ALLOF.forVersion(context.getGeneratorConfig().getSchemaVersion()));
    if (allOf instanceof ArrayNode all) {
      ObjectNode exHolder = all.addObject();
      var jExamples = exHolder.putArray("examples");
      Arrays.stream(examples.value()).forEachOrdered(jExamples::add);
    }
    return new CustomPropertyDefinition(def);
  }

}
```

And I enable the feature like this:
```java
    configBuilder.forFields()
      .withCustomDefinitionProvider(new ExamplesProvider())
```

... then I can use the annotation everywhere:
```java
    @JsonPropertyDescription("""
      Standard processes are a set of predefined processes, which you can customize in your ivy project.
      To enable these custom processes, the library id of the ivy project must be specified here.
      The library id is <group-id>:<project-id> from the ivy project deployment definition.
      The default is 'auto' which means auto detection of standard process in your application """)
    @JsonProperty(defaultValue = "auto")
    @Examples("com.axonivy.portal:portal")
    public String standardProcess;
```

And I get a nice schema out of it:
![examples_schema](https://github.com/victools/jsonschema-generator/assets/15085693/7ef0d345-c2e8-4a10-893a-97273332fade)

Finally; VS-Code offers nice completion for these "examples" : 

![mixingExamplesAndDefaults](https://github.com/victools/jsonschema-generator/assets/15085693/8e0da309-e33d-4a3f-8afd-44bcb8e9f8c9)

**Comment by CarstenWickner** [comment]
HI @ivy-rew,

Thank you for the nice words and thoughtful contribution.

A similar question had been raised in #260 as well, where I provided a possible `InstanceAttributeOverride` configuration based on a Swagger annotation (`@Schema(example = "com.axonivy.portal:portal")`).
I usually take custom definition providers only as the very last resort, although it works of course, since there are certain situations in which you run the risk of getting into an endless loop.

On that previous issue, my response was:
> The "examples" keyword is currently not part of the standard feature set. As one might want to consider the specific data type for which examples are being provided. So far, I didn't bother coming up with a proper implementation.
> But the above should work for textual examples.

I'm still hesitant to provide a generic implementation that only considers string example values and/or is based on a custom annotation.

This is certainly a great alternative for my proposal in #260, if you're not using Swagger annotations already.

**Comment by ivy-rew** [comment]
Thanks a lot for your feedback @CarstenWickner . The pointer to the swagger solution is useful. But I think for now I'd prefer my solution as I don't like to have the swagger libs on my stack, just for this minor use-case.

I feel like examples are not a killer feature while they are just string-arrays. They would be very powerful to me, if I could enrich them with prose, explaining the proposed example value. But it seems like that is not yet supported by VS-Code, which is my main client for the schemas. 

So, there is really no big need to rush ahead with such a feature. Feel free to close this issue for now. 
I just wanted to know whether it makes sense to maintain my custom implementation for it or not.
And maybe it's helpful for other users, that do not like to use the swagger-annotations. ;-)

At any rate; this custom extension shows how nicely your library allows to be extended by users without forking it: well done :100:
