### ISSUE TITLE
Field with special camel-case name (second letter Capital) is ignored by generator

### ISSUE THREAD

**Issue by neumannm** [victools/jsonschema-generator#368]
I think I found a bug today in the jsonschema-generator or the maven plugin. But I am not 100% sure and would love to hear your feedback on this.

I have noticed that one particular field from my class is missing from the generated schema. At first I suspected the long name to be the cause of this, but I also have fields in my classes with longer names. Now I rather suspect it's the way the field is spelled, with a capital letter in second position.

Here's my class:
```
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.extern.jackson.Jacksonized;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@Jacksonized
@JsonIgnoreProperties(ignoreUnknown = true)
public class Test {

	private Header header;
	private TestEnum aBcDefAndSomeMoreCamelCaseHereThatDoesNotMatter;

}

public enum TestEnum {
	ABC,
	DEF,
	;
}
```

The generated schema does not contain the field aBcDefAndSomeMoreCamelCaseHereThatDoesNotMatter:

```
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {...},
  "type" : "object",
  "properties" : {
    "header" : {
      "$ref" : "#/$defs/Header"
    }
  }
}
```

If I would write the field name like this "abcDefAndSomeMoreCamelCaseHereThatDoesNotMatter", it works. But this is no option in my project.

I suspect it has something to do with the fact that we use Lombok here, and that Lombok generates `getABcDefAndSomeMoreCamelCaseHereThatDoesNotMatter` getter, and the schema generator cannot deal with it, but I'm not sure.

**Comment by CarstenWickner** [comment]
Hi @neumannm,

I agree, that there is something off.
My current logic for inferring a method name from the field name is too simplistic, as it only considers the first character -- and not the first two characters, as described in [this StackOverflow answer](https://stackoverflow.com/a/16146215/5127499) and the referenced JavaBeans API Specification:

> **8.8 Capitalization of inferred names.**
> When we use design patterns to infer a property or event name, we need to decide what rules to follow for capitalizing the inferred name. If we extract the name from the middle of a normal mixedCase style Java name then the name will, by default, begin with a capital letter.
> Java programmers are accustomed to having normal identifiers start with lower case letters. Vigorous reviewer input has convinced us that we should follow this same conventional rule for property and event names.
> 
> Thus when we extract a property or event name from the middle of an existing Java name, we normally convert the first character to lower case. However to support the occasional use of all upper-case names, we check if the first two characters of the name are both upper case and if so leave it alone. So for example,
> - “FooBah” becomes “fooBah”
> - “Z” becomes “z”
> - “URL” becomes “URL”

In our case, we're talking about `field -> method` and not `method -> field` as in the JavaBeans API Specification.
Therefore we have to consider both possibilities:
- `getABcDefAndSomeMoreCamelCaseHereThatDoesNotMatter()` would imply a field called `ABcDefAndSomeMoreCamelCaseHereThatDoesNotMatter` (uppercase `A` is wrong)
- `getaBcDefAndSomeMoreCamelCaseHereThatDoesNotMatter()` leads to the actual field name `aBcDefAndSomeMoreCamelCaseHereThatDoesNotMatter`

When you use the `JacksonModule`, `getABcDefAndSomeMoreCamelCaseHereThatDoesNotMatter()´ is not recognized as the getter of the field named `aBcDefAndSomeMoreCamelCaseHereThatDoesNotMatter`.
I, therefore, conclude that the method name generated by the Lombok library doesn't adhere to the JavaBeans API Specification by default.

I see two options for you:
1.  Use a configuration option in Lombok to change the generated getter name:
> `lombok.accessors.capitalization` = [`basic` | `beanspec`] (default: `basic`)
> (added in lombok v1.18.24)
2. Aadding `@JsonProperty("aBcDefAndSomeMoreCamelCaseHereThatDoesNotMatter")` on the affected field to tell Jackson (and implicitly my `JacksonModule`) that this property should have the given name.

The majority opinion seems to be that names like `aField` should be avoided, but sometimes you have to deal with old code/conventions.
I guess I could include a similar configuration option then as Lombok or consider both possibilities as valid getters (assuming the likelihood of both methods existing being very slim in "real" code).

**Comment by CarstenWickner** [comment]
Note: I've extended the built-in logic for what is deemed a "getter" method in #366.
However, that doesn't change the fact that Jackson doesn't recognize the method created by Lombok as getter and consequently ignored the private field without a getter method.

The above two suggestions still apply.

**Comment by neumannm** [comment]
@CarstenWickner thanks a lot for your swift reply. I also researched more on the topic after I posted here, and found out about the Lombok/Jackson issue with different naming conventions resp. expectations on accessor names.

Thanks also for your suggestions - using a lombok.config file and setting `lombok.accessors.capitalization = beanspec` did the trick for us. 😃

**Comment by CarstenWickner** [comment]
Release [v4.32.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.32.0) has been published, including the support for `isBoolean` fields with `isBoolean()` getters.
