### ISSUE TITLE
Support `Schema#requiredMode` in swagger-2-module

### ISSUE THREAD

**Issue by linuxPenguin** [victools/jsonschema-generator#371]
[swagger-core 2.2.5](https://github.com/swagger-api/swagger-core/releases/tag/v2.2.5) deprecated [Schema#required](https://www.javadoc.io/doc/io.swagger.core.v3/swagger-annotations/2.2.5/io/swagger/v3/oas/annotations/media/Schema.html#required--) in favor of a [new element called requiredMode](https://www.javadoc.io/doc/io.swagger.core.v3/swagger-annotations/2.2.5/io/swagger/v3/oas/annotations/media/Schema.html#requiredMode--). The purpose of this issue is to add support for this new element to jsonschema-module-swagger-2.

**Comment by jl-martins** [comment]
Thank you @CarstenWickner!

**Comment by CarstenWickner** [comment]
Hi @jl-martins,

It was an easy change.
Still pending release though.

Maybe I'll trigger that tonight.

**Comment by CarstenWickner** [comment]
Release [v4.32.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.32.0) has been published, including this change.
