### ISSUE TITLE
javax.validation... error message from annotation to validator error message

### ISSUE THREAD

**Issue by VovkaSOL** [victools/jsonschema-generator#373]
Hi developers, annotation like @NotNull(message="xxxxxx") have error message text xxx. Json schema support's message for concrete validation(
  "message": {
    "maxItems" : "MaxItem must be 3 only",
    "type" : "Invalid type"
  }
)
Please add options in JavaxValidationOption enum for support error message copy in schema

**Comment by CarstenWickner** [comment]
Hi @VovkaSOL,

Can you please point me to the JSON Schema Specification where this is described?
I couldn't find it myself, unfortunately.

**Comment by VovkaSOL** [comment]
@CarstenWickner i can't find it in specification, but i found it in stackoverflow :-) https://stackoverflow.com/questions/40423376/json-schema-validator-custom-message
some PR in github https://github.com/json-schema-org/json-schema-spec/issues/643

victools/jsonschema-generator support this error messages format too :-)
...
  "properties": {
    "beneficiary": {
      "type": "object",
      "message": {
        "type": "type error text",
        "required": "required error text"
      },
...

**Comment by VovkaSOL** [comment]
found this https://json-schema.org/draft/2020-12/json-schema-core.html @CarstenWickner

**Comment by VovkaSOL** [comment]
Very strange situation with custom messages for json schema validations errors, specification says "

[12.3.4. ](https://json-schema.org/draft/2020-12/json-schema-core.html#section-12.3.4)[Error or Annotation](https://json-schema.org/draft/2020-12/json-schema-core.html#name-error-or-annotation)
The error or annotation that is produced by the validation.

For errors, the specific wording for the message is not defined by this specification. Implementations will need to provide this.

For annotations, each keyword that produces an annotation specifies its format. By default, it is the keyword's value.

The JSON key for failed validations is "error"; for successful validations it is "annotation".
" 

but this message blocks https://stackoverflow.com/questions/40423376/json-schema-validator-custom-message work good in victools/jsonschema-generator.

**Comment by CarstenWickner** [comment]
With this not being a standard feature in the specification, I'm hesitant to add it as standard feature in the generator here. Additionally, those validation annotations may specify a message key, which also would need to be resolved first.

Through the existing configuration options, you're able to add this yourself though.
Let me know, if you need assistance with that configuration and I'll be happy assist in creating an example for it.

**Comment by fernandosesma** [comment]
Hi @CarstenWickner,

I've encountered the issue discussed here, can you still create an example of how this can be accomplished with the existing configuration options. Thanks!

**Comment by CarstenWickner** [comment]
Hi @fernandosesma,

I've created a basic example and will be adding it to the repository.
Refer to PR #390 for a possible configuration and the corresponding schema output.

In order to cover all possible validation annotations, I'm afraid you'll have to do considerable custom configurations.
But the example should give you an idea how it can be achieved in general.
I hope that helps.

**Comment by fernandosesma** [comment]
> Hi @fernandosesma,
> 
> I've created a basic example and will be adding it to the repository. Refer to PR #390 for a possible configuration and the corresponding schema output.
> 
> In order to cover all possible validation annotations, I'm afraid you'll have to do considerable custom configurations. But the example should give you an idea how it can be achieved in general. I hope that helps.

Great! This worked like a charm. Thanks so much!
