### ISSUE TITLE
Enable the maven plugin to read Module class from `src/test/...`? 

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#383]
Hi, I'm using the jsonschema library to generate some json schemas before running my integration tests. All my tests are in a maven module within `module-name/src/test/kotlin/...`. I put my SchemaModule class in `src/test/kotlin/utils/MyModule`, and I can see that it successfully compiles to a .class file during the maven test-compile step. However, the jsonschema maven plugin classloader is unable to find it. After I moved MyModule to `src/main/kotlin/utils/MyModule`, the plugin found the class successfully. 

Can we configure the classloader of the maven plugin to be able to read Module classes out of `src/test/....` too? (I am able to see the MyModule.class file within the `target/test-classes/...` folder that maven generates during compilation?

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

I'm not so familiar with the inner workings of Maven. I suppose you could bundle the schema configuration module into its own artifact and declare that as explicit dependency of the Maven plugin, to make it visible to that, without having to mix it with your actual application code.

At this point, I'd also just try to search for generic Maven solutions, as this is not particular to the schema generator plugin I suppose.
However, if you do find a configuration suggestion or have an idea of how to adjust the class loading to include test classes as well, I'm all for it.
The current implementation is very simplistic:
https://github.com/victools/jsonschema-generator/blob/480935c3d50f8352b37b17855edcaca67c509643/jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java#L512

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

I've played around with this and made a small change to generally allow what you're asking here.
Besides that adjustment in the plugin itself, you will then also need to execute the schema generation in the `<phase>test-compile</phase>` otherwise the Module class wouldn't have been compiled yet when the schema generation is performed during the default `<phase>compile</phase>`.
Refer to #389 for the documentation I'm adding for this.

**Comment by CarstenWickner** [comment]
Release [v4.32.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.32.0) has been published, including this change.

**Comment by takanuva15** [comment]
One issue I ran into for my use-case in case someone else stumbles on this: 

I was generating schemas during the `test-compile` phase and storing them in `./src/test/resources/schemas/model/`. However, maven runs its `process-test-resources` before it does `test-compile`, which means it copies over all the stuff in `src/test/resources` before I ever generated my schemas. So, once I generated my schemas, those schemas never made it into the final build directory within the classpath because maven never copied them over.

To remedy this, I had to define a custom `execution` within the `maven-resources-plugin` to copy over my newly-generated schemas:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <executions>
        <execution>
            <id>copy-autogenerated-model-schemas-to-test-resources</id>
            <phase>test-compile</phase>
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <configuration>
                <resources>
                    <resource>
                        <directory>${project.basedir}/src/test/resources/schemas/model</directory>
                    </resource>
                </resources>
                <outputDirectory>${project.build.testOutputDirectory}/schemas/model</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
```

With this execution, maven was now copying over my schemas into the build directory too after `test-compile`.
