### ISSUE TITLE
How to add `unevaluatedProperties: false` to all schemas autogenerated by the maven plugin?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#387]
Hi, I'm using the maven plugin to autogenerate schemas for a large number of model classes. I will end up using these schemas for validating my API responses, so I would like to make sure all schemas have `unevaluatedProperties: false` at the root level so that I don't see any unexpected properties. Is there an easy way to configure this? Or would I need to define a custom module and add that to the `<module>` list within the maven plugin's config?

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

If you only want it on the root schema, then yes: it'd probably be easiest to include it in a custom module (as per my response to your other question #386).
The built-in `Option.FORBIDDEN_ADDITIONAL_PROPERTIES_BY_DEFAULT` would add it in a lot of other places and poses the risk of making some schemas too strict.

**Comment by takanuva15** [comment]
Thanks, I solved this issue based on your response in #386. I put [a solution](https://github.com/victools/jsonschema-generator/issues/386#issuecomment-1777400951) in there that worked for me.
