### ISSUE TITLE
Problem generating `List<String>` where the list can be null and array elements can be null

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#391]
Hi, I have a class which I've simulated as the following:
```java
class Dummy {
    private List<String> myStrings;
}
```

I want to generate a schema where the `myStrings` field can be null, and the elements of myStrings can contain null.

The following code works for allowing `myStrings` to be null, but it still forces the elements of myStrings to be Strings only (doesn't allow nulls):
```java
SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
            .with(Option.NULLABLE_ARRAY_ITEMS_ALLOWED)
            .with(Option.NULLABLE_FIELDS_BY_DEFAULT);
SchemaGeneratorConfig config = configBuilder.build();
SchemaGenerator generator = new SchemaGenerator(config);
JsonNode jsonSchema = generator.generateSchema(YourClass.class);

System.out.println(jsonSchema.toPrettyString());
```

The schema that gets generated is this:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "myStrings": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    }
  }
}
```
^The `items` section should allow type `string` or type `null` here for what I need

From inspection of the docs, it sounds like `Option.NULLABLE_ARRAY_ITEMS_ALLOWED` should make the `items` of the array nullable, but that doesn't seem to happen here.

Note: I'm using the maven plugin to autogenerate schemas for a ton of model classes

(On a related note, it seems Option 23 in the docs [here](https://victools.github.io/jsonschema-generator/#generator-options) is missing an underscore :P)

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

First of all: Thanks for finding the missing underscore. 😉

As for the `Option.NULLABLE_ARRAY_ITEMS_ALLOWED`, there is a caveat here:
The option says "allowed" not "nullable array items by default", i.e., note the last part in the documentation saying:
> The schema <code>type</code> for the items in an array (in case of a field's value or method's return value being a container/array) allows <code>null</code>, if the corresponding configuration explicitly says so. Otherwise, they're still deemed not null-able by default.

"if the corresponding configuration explicitly says so" means, you need to add a nullable check which returns `true`. E.g., for making all array items `null`-able, it'd be something like:
```java
configBuilder.forFields()
    .withNullableCheck(field -> field.isFakeContainerItemScope() ? Boolean.TRUE : null);
```

**Comment by takanuva15** [comment]
Gotcha thanks that worked. I have a lot of model classes that I am autogenerating schemas for - if there is a specific model class with a member array which I want to allow nulls for, is there an annotation or something I can put on that specific array member so the autogenerated schema will allow nulls just for that array but not arrays in other model classes?

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

Sure, you could use a `@Nullable` annotation like this:
```java
@NotNull
private List<@Nullable String> requiredListContainingNullableStrings;
```
The configuration would be like this:
```java
configBuilder.forFields().withNullableCheck(field -> (field.isFakeContainerItemScope()
        && field.getContainerItemAnnotationConsideringFieldAndGetter(Nullable.class) != null)
        ? Boolean.TRUE : null);
```
