### ISSUE TITLE
Using `Jackson` module seems to ignore properties that begin with 2+ uppercase letters?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#404]
Hi, I'm using this library to generate schemas for some classes that use `Jackson` annotations. One weird issue I've found is that if I have a class with a property that starts with 2+ uppercase letters, it seems the schema generator ignores it completely during schema generation. 

Sample class:
```
@Data
public class Dog {
	private int PScore;
}
```

Schema output with Jackson module enabled:
```
$schema: https://json-schema.org/draft/2020-12/schema
type: object
```

This seems like unexpected behavior - how can I fix it so it will generate schema props for class members starting with 2+ uppercase letters?

**Comment by takanuva15** [comment]
Never mind, I just saw that this conversation was hashed out with solutions in [this older issue](https://github.com/victools/jsonschema-generator/issues/368). Thanks for clarifying the issue in that thread.

**Comment by takanuva15** [comment]
Actually as a follow-up question, could we add an option/plugin to the Jackson module to parse the "basic" getters that Lombok generates instead of having to reconfigure our Lombok getters to match the beanspec? (I'm dealing with a bunch of legacy code unfortunately lol)

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

Was about to point to that issue as well.
If both given options there (changing Lombok configuration or adding `@JsonProperty` annotations) are not acceptable, then that means you need to circumvent the standard `JacksonModule`'s way of including/excluding properties.
The responsible piece of code should be this:
https://github.com/victools/jsonschema-generator/blob/81470da6f6328a01d3c45fc36e45b91f726f55fd/jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java#L291-L292

The `JacksonModule#shouldIgnoreField()` method is `protected` exactly for this kind of scenario: allowing you to create a subtype of the `JacksonModule` to alter some behavior while leaving the rest intact.
If you really only care about this edge case, you could do something along the lines of this:
```java
JacksonModule module = new JacksonModule() {
    @Override
    protected boolean shouldIgnoreField(FieldScope field) {
        return super.shouldIgnoreField(field) && !field.getName().matches("$[A-Z]+.*");
    }
};
```

**Comment by takanuva15** [comment]
I tried your code and it didn't work - then I realized you put a `$` sign at the start of your regex instead of `^` haha. Classic typo mistake. Also, since I was manually including the new module like this,
```
private class MyJacksonModule extends JacksonModule {
	@Override
	protected boolean shouldIgnoreField(FieldScope field) {
		return super.shouldIgnoreField(field) && !field.getName().matches("^[A-Z]+.*");
	}
}

...

builder.with(new MyJacksonModule());
```
I had to delete the existing `JacksonModule` I had specified in the plugin's xml `<module>` list.

One problem I'm facing with this approach is that the field-name that gets added to the jsonschema does not match what Jackson returns by default for such a field being serialized from an API. Take this code for example:
```
@SneakyThrows
public static void main(String[] args )
{
    var dog = new Dog();
    dog.setPScore(10);

    var json = new ObjectMapper().writeValueAsString(dog);
    System.out.println(json);
}
```
The output that gets printed for the json looks like this: `{"pscore":10}`

But the field name that gets added to Dog-schema is this:
```
properties:
  PScore:
    type: integer
```

Do you know why that discrepancy is happening?

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

That seems to be a particularity with variable names starting with uppercase characters, which is unconventional I suppose.
Nevertheless, you can work around it with something like this:
```java
configBuilder.forFields()
        .withPropertyNameOverrideResolver(this::getPropertyNameOverride);
```
```java
private String getPropertyNameOverride(MemberScope<?, ?> scope) {
    Pattern regExUppercaseStart = Pattern.compile("^([A-Z]{2,})(.*)$");
    Matcher matcher = regExUppercaseStart.matcher(scope.getName());
    if (!matcher.matches()) {
        return null;
    }
    // change leading uppercase letters to lowercase while leaving the rest unchanged
    return matcher.group(1).toLowerCase() + matcher.group(2);
}
```
