### ISSUE TITLE
Getter not found for properties with 1st lowercase and 2nd uppercase characters

### ISSUE THREAD

**Issue by bmaizel** [victools/jsonschema-generator#408]
We have an API class with field "oBONumber".
The jsonschema-generator looks for the getter with name "getOBONumber".
The responsible code is hier: com.github.victools.jsonschema.generator.FieldScope#doFindGetter
The actual getter name in our class is "getoBONumber", and it is not found.

The class was actually generated by the openapi-generator. (Please, don't ask why we generate
schema from the class, that was itself generated from schema :)
I investigated for the reason, why this getter name was generated, and found it hier, line 2150:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java

```
       // Let the property name capitalized
        // except when the first letter of the property name is lowercase and the second letter is uppercase
        // Refer to section 8.8: Capitalization of inferred names of the JavaBeans API specification
        // http://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf)

```

The referenced document actually says, that field "OBONumber" (with capital "O" as the 1st char)
must have getter name "getOBONumber". And I understand the reason why "oBONumber" shold not
have the same.

Therefore, I suggest to fix the algorithm in the FieldScope#doFindGetter as following.
If field name does not start with first lowercase and second uppercase, do as before.
Otherwise look for the getter name "get" + field name.
If it is not found, check if a colliding field with the same name with first letter uppercase exist.
If the colliding field does not exist, look for "get" + field name capitalized, as before.

I.e. look first for "getoBONumber". If it does not exist, check if the field "OBONumber" exists,
and if not, look for "getOBONumber".

This way we become compatible with the javabeans spec, while retaining the maximum backward compatibility.

**Comment by CarstenWickner** [comment]
Hi @bmaizel,

What you're asking for was introduced in the last release [v4.32.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.32.0).
I assume you're using an older version of the library right now.

I suggest you update and give it another try. :smiley:

**Comment by bmaizel** [comment]
I was on 4.31.1, update solved the issue, thank you!
