### ISSUE TITLE
Release including #396?

### ISSUE THREAD

**Issue by magicDGS** [victools/jsonschema-generator#416]
Hello @CarstenWickner, I am waiting for a new release containing https://github.com/victools/jsonschema-generator/issues/396. Any estimate time for this? Thank you very much!

**Comment by CarstenWickner** [comment]
Hi @magicDGS,

I've just published [v4.33.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.33.0).
Should take about 30 minutes to be available on Maven Central and up to a couple of hours to be fully propagated everywhere.

**Comment by magicDGS** [comment]
Thanks a lot, @CarstenWickner!
