### ISSUE TITLE
Jackson JsonProperty.defaultValue should be a default value in json schema

### ISSUE THREAD

**Issue by willome** [victools/jsonschema-generator#418]
A pojo like this :
```java
public class SampleEvent {
	@JsonProperty(required = true, defaultValue = "test")
	private String name;
}
```

maven plugin is generating 
```json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string"
    }
  },
  "required" : ["name" ]
}
```

I would expect the default value: 
```json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string",
      "default": "test"
    }
  },
  "required" : ["name" ]
}
```

**Comment by CarstenWickner** [comment]
Hi @willome,

The default value is not supported to be looked up automatically. The motivation being, that one might want to apply some formatting of the annotated default value, which cannot be easily achieved in a generic way.

You can define a custom `Module` to include the default values through the Maven plugin.

**Comment by CarstenWickner** [comment]
For completeness' sake:
Please refer to this FAQ entry: https://victools.github.io/jsonschema-generator/#how-to-populate-default-values
The example code matches your specific use case:
```java
configBuilder.forFields().withDefaultResolver(field -> {
    JsonProperty annotation = field.getAnnotationConsideringFieldAndGetter(JsonProperty.class);
    return annotation == null || annotation.defaultValue().isEmpty() ? null : annotation.defaultValue();
});
```
