### ISSUE TITLE
Question - enum of Enum property value

### ISSUE THREAD

**Issue by MiltosD** [victools/jsonschema-generator#419]
I woulld like to know whether I can output enums from the "label" of an Enum e.g.

```java
public enum ConnectionType {
    TOKEN("token-connection"),
    SSH("ssh-connection");

    private final String name;

    ConnectionType(String name) {
        this.name = name;
    }
}
```

So I want this:
```json
"enum": [
                "token-connection",
                "ssh-connection"
            ]
```

instead of 
```json
"enum": [
                "TOKEN",
                "SSH"
            ]
```

Is this doable?

**Comment by CarstenWickner** [comment]
Hi @MiltosD,

There are various options concerning enums as I tried to summarise in the documentation:
https://victools.github.io/jsonschema-generator/#what-about-enums

Your example suggests that you're already using the default `Option.FLATTENED_ENUMS`.
Perhaps you want to:
1. Include the `JacksonModule` with `JacksonOption.FLATTENED_ENUMS_FROM_JSONVALUE`
2. Adding a `getLabel()` method on your enum types and annotate it with `@JsonValue`.

Alternatively re-implement an equivalent to what the `JacksonModule` does internally: [CustomEnumDefinitionProvider.java](https://github.com/victools/jsonschema-generator/blob/main/jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/CustomEnumDefinitionProvider.java)

**Comment by MiltosD** [comment]
Thank you very much. I will give it a try

**Comment by MiltosD** [comment]
1 and 2 seem to work just fine. Thank you. Any idea how I can output a custom Jackson annotation? For example a "placeholder" property..

**Comment by CarstenWickner** [comment]
Hi @MiltosD,

I'm unsure what you mean.

If you want to add attributes to a generated (sub)schema, perhaps you mean the `InstanceAttributeOverride`/`TypeAttributteOverride` feature as mentioned [here](https://victools.github.io/jsonschema-generator/#generator-advanced-configurations)?

Perhaps you can provide a more concrete example (Java type + expected schema)?

**Comment by MiltosD** [comment]
Something like the following:

```
"name": {
      "type": "string",
      "description": "This is description for the name field",
      "placeholder": "A placeholder short text for the UI input field"
  }
```

I found out that you can define your own annotations with jackson

```
@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface JsonPlaceholder {
    String value();
}

public class JsonPlaceholderSerializer extends StdSerializer<String> implements ContextualSerializer {

    private String placeholder;

    public JsonPlaceholderSerializer() {
        super(String.class);
    }

    public JsonPlaceholderSerializer(String placeholderText) {
        super(String.class);
        this.placeholder = placeholderText;
    }

    @Override
    public void serialize(String value, JsonGenerator jgen, SerializerProvider provider) throws IOException {
        jgen.writeString(this.placeholder);
    }

    @Override
    public JsonSerializer<?> createContextual(SerializerProvider prov, BeanProperty property) throws JsonMappingException {
        String placeholderText = null;
        JsonPlaceholder placeholder1 = null;
        if (property != null) {
            placeholder1 = property.getAnnotation(JsonPlaceholder.class);
        }
        if (placeholder1 != null) {
            placeholderText = placeholder1.value();
        }
        return new JsonPlaceholderSerializer(placeholderText);
    }
}
```
and use that like

```
@JsonProperty("name")
@JsonPropertyDescription("This is description for the name field")
@JsonSerialize(using = JsonPlaceholderSerializer.class)
@JsonPlaceholder("A placeholder short text for the UI input field")
private String name;
```

**Comment by CarstenWickner** [comment]
Hi @MiltosD,

Two notes:
1. This has nothing to do with enums anymore, i.e., a new discussion might have been good instead of continuing on this issue.
2. What you're describing is simply a custom annotation, that has also nothing to do with Jackson as such. You just happen to have a special Jackson serializer to handle it.

For deriving custom attributes (such as your `"placeholder"`) from any annotation (custom or otherwise), you can use the aforementioned `InstanceAttributeOverride`/`TypeAttributteOverride` feature as described [in the documentation](https://victools.github.io/jsonschema-generator/#generator-advanced-configurations).
An example can be found [in the examples directory](https://github.com/victools/jsonschema-generator/blob/main/jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/ValidationErrorMessageExample.java) as well.
Something like this:
```java
configBuilder.forFields().withInstanceAttributeOverride((schema, member, context) -> {
        JsonPlaceholder annotation;
        if (member.isFakeContainerItemScope()) {
            annotation = member.getContainerItemAnnotationConsideringFieldAndGetterIfSupported(JsonPlaceholder.class);
        } else {
            annotation = member.getAnnotationConsideringFieldAndGetterIfSupported(JsonPlaceholder.class);
        }
        if (annotation != null) {
            schema.put("placeholder", annotation.value());
        }
});
```

**Comment by MiltosD** [comment]
Thank you!
