### ISSUE TITLE
.with(new JacksonModule())   aBd not should Ignore this  Field

### ISSUE THREAD

**Issue by TanqiZhou** [victools/jsonschema-generator#427]
aBd   not should Ignore
`@Data
public class User {
    private Integer aBd;
    private Integer storeId;
}`

`{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "storeId" : {
      "type" : "integer"
    }
}`

**Comment by CarstenWickner** [comment]
HI @TanqiZhou,

Please refer to my answer on https://github.com/victools/jsonschema-generator/issues/368

**Comment by TanqiZhou** [comment]
this is 4.33.1 version

**Comment by CarstenWickner** [comment]
Hi @TanqiZhou,

then you're likely missing the same `lombok.accessors.capitalization = beanspec` setting as the one asking on the duplicate issue.
It's an old Lombok short-coming that they don't adhere to the Java Beans specification by default and require this extra bit of configuration to make it work.

**Comment by TanqiZhou** [comment]
thank you!
