### ISSUE TITLE
How to document a class containing multiple map strings?

### ISSUE THREAD

**Issue by tadhgpearson** [victools/jsonschema-generator#430]
First, thanks for putting this great toolset together. I really appreciate being able to have my code and documentation in the same place :)

I am struggling to document an schema which containing inputs for various machine learning models.

The class has two fields like this

```java
    private Map<String, ScoringData> goodFeatures;
    private Map<String, ScoringData> badFeatures;
```

where each of the map keys is a set of feature IDs, such as `location`, `language`, etc, that goodFeatures and badFeatures have different keysets, and then the ScoringData value is a class containing a bunch of double primitives I can feed to a model.

I'd like to be able to document the list of keys to this map, such that I end up with a JSON schema like

```json
    "goodFeatures": {
      "type": "object",
      "properties": {
        "location": {
          "type": "object",
          "properties": {
           ... details of the scoing data ...
          },
        },
        "lang": {
          "type": "object",
          "properties": {
            ...
          },
        }
      },
      "required": [
        "location",
        "lang"
      ]
    },
    "badFeatures": {
      ... same kinda thing ...
    }
```

I've been reading the examples and documentation... and it doesn't seem this is possible. Am I missing something?  (edited to improve formatting)

**Comment by CarstenWickner** [comment]
Hi @tadhgpearson,

Thank you for the kind praise.

As for your question: pretty much anything is possible. The schema generator allows you to take over at various points and provide custom schema portions.

The question is: do you want to define these constraints in your code (e.g., via some annotations) or should this aspect only be defined inside your schema generator configuration?

**Comment by tadhgpearson** [comment]
Thanks for your quick followup Carsten! I'm trying to do by annotation rather than in the schema config generator. This allows me to reuse the existing schema generator config that's already in my app. I don't want to have this end up in additionalProperties - I'd rather define the properties.

There are enough features going into the model that all  have the same shape that doing it with a map saves a ton of boilerplate code... although its true that using a real object would definitely simplify the documentation. I hadn't thought of that approach, but if is saves a ton of documentation boilerplate, then maybe it's better to go with a strongly-typed object.

**Comment by CarstenWickner** [comment]
An additional advantage of a strongly-typed object: type safety.

Just ask a TypeScript developer what they think is most sorely lacking feature in plain JavaScript, and the answer may very well be: type safety.

Today, there are nicer ways to reduce boilerplate code than using a `Map` and unenforced conventions about its contents, e.g., Java records or in older Java versions: libraries like lombok.

I'm closing this accordingly then, as I'm a big fan of type safety and agree with you that it's the preferable option here. 😃

**Comment by tadhgpearson** [comment]
I agree with the outcome @CarstenWickner ... Just to add color to your comment above, in my experience the use cases cuts one of these two ways

1. The case you describe: the whole thing is strongly typed in code. You can use real fields and document them with victools. There's lots of painful boilerplate but most of it can be produced for you by Lombok
2. The feature is untyped, and likely that's for a good reason (such as, it's driven by a loosely-typed config file to avoid releasing pain.) Now you have a map, and you can't document the fields properly anyway because it's driven by something external that's not necessarily typed. In this case Victools can't save you anyway... so we don't have to think about it here.
