### ISSUE TITLE
Maven plugin with Jackson and ACCEPT_SINGLE_VALUE_AS_ARRAY

### ISSUE THREAD

**Issue by Boereck** [victools/jsonschema-generator#458]
Hi,

I am using the `jsonschema-maven-plugin` to generate a JSON Schema for Jackson annotated classes. On the ObjectMapper in the code I set the property `com.fasterxml.jackson.databind.DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY` to `true`. I cannot find a configuration option for the Jackson module of the maven plugin. Is there an option I missed, or is it not (yet) possible to configure such feature on the maven plugin?

Thanks for the work on this projekt, and best regards,
Max

**Comment by CarstenWickner** [comment]
Hi @Boereck,
Indeed, this is currently not supported out-of-the-box.

But I've created an example of how this can be easily achieved through configuration (for use via the Maven plugin, you'd have to wrap it in a `Module` of your own): [`SingleArrayItemExample`](https://github.com/victools/jsonschema-generator/blob/main/jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/SingleArrayItemExample.java)

Basically you can do this:
```java
configBuilder.forFields()
        .withTargetTypeOverridesResolver(scope -> scope.isContainerType() && !scope.isFakeContainerItemScope()
                Arrays.asList(scope.getContainerItemType(), scope.getType()) : null);
```
For a data type like this:
``` java
    class Example {
        @NotNull
        public List<ArrayItem> someArray;
    }

    class ArrayItem {
        public String value;
    }
```
The generated schema ends up with an `anyOf` containing the single item type and an array of the item type:
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$defs": {
        "ArrayItem": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        }
    },
    "type": "object",
    "properties": {
        "someArray": {
            "anyOf": [
                {
                    "$ref": "#/$defs/ArrayItem"
                }, {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/ArrayItem"
                    }
                }
            ]
        }
    }
}
```

**Comment by Boereck** [comment]
Wow, that was fast! Thank you so much!

**Comment by CarstenWickner** [comment]
The release of [v4.36.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.36.0) was also done.
It should be available in a couple of hours.

**Comment by Boereck** [comment]
Awesome! Works like a charm. Thanks again!
