### ISSUE TITLE
If it is a nested Generics, how to generate jsonschema

### ISSUE THREAD

**Issue by hhtqaq** [victools/jsonschema-generator#461]
like this: `A<List<B>>`

**Comment by CarstenWickner** [comment]
Hi @hhtqaq,

The `SchemaGenerator.generateSchema(Type, Type...)` is explicitly not limited to `Class` arguments.
You can also provide classmate `ResolvedType` instances, which support nested generic parameters.

For your example, that could look something like this then:
```java
SchemaGeneratorConfig config = configBuilder.build();
TypeContext typeContext = TypeContextFactory.createDefaultTypeContext(config);
ResolvedType listOfB = typeContext.resolve(List.class, B.class); // List<B>
ResolvedType aOfListOfB = typeContext.resolve(A.class, listOfB); // A<List<B>>
new SchemaGenerator(config).generateSchema(aOfListOfB);
```
You could have used the raw types for a single level of parameters still, but I assume you're aware and therefore asked for nested generics specifically. Just for completeness' sake (in case that is good enough for others):
```java
new SchemaGenerator(config).generateSchema(List.class, B); // List<B>
```
