### ISSUE TITLE
Please put an example of the class IfPresentAlsoRequire of the dependentRequired in the github

### ISSUE THREAD

**Issue by RafaelRfs** [victools/jsonschema-generator#463]
Hi, how are you?

I would like to thank you by the excelent work that are you doing ...

But can you please put a little example of the class  "IfPresentAlsoRequire.class" ... I have tried a lot to do to implement but i couldn't ...

I need to create a contract with a condition, if the field was determined by an another in the domain class, i need to validate it against  the contract ... Like this example:

with insurance is update contract enum i need to validate if the descriptions was filled, but otherwise i let the flow pass ...

I think with the dependency requires resolver will work well, i tried to implement but i couldn't find more on the internet ...

Please, can you help me?

`withDependentRequiresResolver()` is expecting the names of other properties to be returned, which should be deemed "required", if the property represented by the given field/method is present. The results of all registered resolvers are being combined.

```java
configBuilder.forFields()
    .withDependentRequiresResolver(field -> Optional
        .ofNullable(field.getAnnotationConsideringFieldAndGetter(IfPresentAlsoRequire.class))
        .map(IfPresentAlsoRequire::value)
        .map(Arrays::asList)
        .orElse(null));
configBuilder.forMethods()
    .withDependentRequiresResolver(method -> Optional.ofNullable(method.findGetterField())
        .map(FieldScope::getSchemaPropertyName)
        .map(Collections::singletonList)
        .orElse(null));
```

This link:
https://victools.github.io/jsonschema-generator/#quot-required-quot-keyword

Thanks by reading ...
Sincerely

Rafael

**Comment by CarstenWickner** [comment]
Hi @RafaelRfs,

Sure thing.
Please take a look at the full example added in PR #464.

I suspect you were merely missing the `@Retention(RetentionPolicy.RUNTIME)` meta annotation, to preserve it during compilation and thereby allow the schema generator to still encounter the `@IfPresentAlsoRequire` annotation when it analyses the compiled byte code version of your classes.

```java
@Target({ElementType.FIELD, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@interface IfPresentAlsoRequire {
    String[] value();
}
```

**Comment by RafaelRfs** [comment]
Thanks very much @CarstenWickner :)
You saved me a lot !  :)
