### ISSUE TITLE
Kotlin: Generating 'required' schema attribute?

### ISSUE THREAD

**Issue by yahorbarkouski** [victools/jsonschema-generator#466]
Hey! Wondering if it's possible to generate a schema with 'required' attribute like in the following output:
```json
"schema": {
  "type": "object",
  "properties": {
    "steps": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "explanation": {
            "type": "string"
          },
          "output": {
            "type": "string"
          }
        },
        "required": ["explanation", "output"], <- THIS LINE
        "additionalProperties": false
      }
    },
    "final_answer": {
      "type": "string"
    }
  },
  "required": ["steps", "final_answer"], <- THIS LINE
  "additionalProperties": false
}
```
If so, what option/setting should I use?

I was trying to do so by using `withRequiredCheck` (even added NotNull JetBrains annotations:)), but no luck:
```kotlin
val configBuilder = SchemaGeneratorConfigBuilder(DRAFT_2020_12, PLAIN_JSON)
      .with(FORBIDDEN_ADDITIONAL_PROPERTIES_BY_DEFAULT)
     
configBuilder.forFields()
      .withRequiredCheck(FieldRequiredCheck { field: Field -> field.isAnnotationPresent(NotNull::class.java) })
```

**Comment by yahorbarkouski** [comment]
@CarstenWickner  `@field:NotNull` doesn't work, unfortunately, but I get the direction, thank you so much!

**Comment by emeraldhieu** [comment]
@yahorbarkouski What's your solution? I'm looking for the same thing. 
I think this feature should be implemented.

**Comment by emeraldhieu** [comment]
Ok. It works after using Springs's `NonNull` and `Nullable`.

**Comment by piotrp** [comment]
For Kotlin you can check for `org.jetbrains.annotations.NotNull` / `org.jetbrains.annotations.Nullable` - they are automatically added by Kotlin compiler.

**Comment by piotrp** [comment]
Or:
```kotlin
configBuilder.forFields()
    .withRequiredCheck { it.rawMember.kotlinProperty?.returnType?.isMarkedNullable == false }
```
This can be also done from pure Java:

https://github.com/springdoc/springdoc-openapi/blob/830a98a0deef6d4758513e61a420433b3bc7c6c4/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/utils/SchemaUtils.java#L153-L159
