### ISSUE TITLE
Ignore all abstract classes during generation?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#476]
Hi, is there a way to configure the generator to skip generating schemas for all abstract classes in a package?

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

The solution depends on what you mean by "to skip generating schemas".
Whether you want to ignore fields/methods with an abstract associated type or to return an empty `CustomDefinition`, you can use a `ResolvedType`'s `isAbstract()` method to identify those cases.
For limiting such a check to particular package, you can orient yourself on the [ExternalRefPackageExample](https://github.com/victools/jsonschema-generator/blob/main/jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/ExternalRefPackageExample.java) you were already looking at before.

**Comment by CarstenWickner** [comment]
@takanuva15 are you referring to the Maven plugin?
I didn't get that before. There, the answer is currently "not really". Unless you follow a particular naming pattern, e.g., always adding a prefix to abstract classes and interfaces like `IAnimal` or `AbstractAnimal` or keep them in a distinct subpackage. The purely name-based filtering mechanism in the Maven plugin is currently incapable of skipping classes based on their content.
But it's worth exploring and should be simple enough to add actually. I merely need to find the time for it. 😬

**Comment by CarstenWickner** [comment]
With the next release, there will be two new config flags for the Maven plugin:
- `<skipAbstractTypes>true</skipAbstractTypes>`
- `<skipInterfaces>true</skipInterfaces>`

Not sure when I'll trigger the next release yet though.

**Comment by CarstenWickner** [comment]
Release [v4.37.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.37.0) has just been published containing the new maven plugin configuration parameters.
