### ISSUE TITLE
Handling nullable types in a custom way

### ISSUE THREAD

**Issue by catadincu** [victools/jsonschema-generator#482]
Hey!

I need to handle property nullability in a very specific way when generating a JSON Schema, i.e. nullable types need to have their type specified in an `anyOf` construct, instead of a `type` array.

e.g.:
```
"my_special_property" : {
  "anyOf" : [ {
    "type" : "string"
  }, {
    "type" : "null"
  } ]
```

what's the best way of being able to generate such a schema, for properties annotated with `@Nullable`? This includes complex types (non-primitives), custom types (defined in the schema) as well as interfaces which have multiple implementations.

I implemented this support for strings with a `CustomPropertyDefinitionProvider`, but it doesn't scale well - I'd like to generify the support for basically anything.

I've been banging my head against the wall for a bit with this one, and I figured a question here would be good.

**Comment by CarstenWickner** [comment]
Hi @catadincu,

The `"type": ["null", "string"]` option is something baked into the generator at the moment, in order to benefit from this more concise way of expressing the same thing.

I started looking into this but am struggling to dedicate enough time.
Can't promise anything yet. How urgent do you need this?

**Comment by catadincu** [comment]
No worries @CarstenWickner ! I started implementing a `CustomPropertyDefinitionProvider` which gets applied on fields marked as `@Nullable`.

So far it's working pretty well, with the exception of properties whose types are interfaces (which can have multiple implementations) - i'm struggling to figure out a way to flatten the `anyOf`s in the generated type:

e.g.:
```
"interface" : {
          "anyOf" : [ {
            "anyOf" : [ {
              "$ref" : "#/$defs/Subtype1"
            }, {
              "$ref" : "#/$defs/Subtype2"
            }, {
              "type" : "null"
            } ]
```

**Comment by CarstenWickner** [comment]
How are you resolving the interfaces to their subtypes?
Are you using a "SubtypeResolver" or handling it manually in another "Custom Definition Provider"?
The former might yield cleaner results than the latter.

Would have to look at a full concrete example to tell exactly though.

**Comment by catadincu** [comment]
behind the scenes it's using the SubtypeResolver, not doing anything special yet. Not sure if this is the right way of doing it, but here it goes.

```
private static class NullableTypeCustomDefinitionProvider
      implements CustomPropertyDefinitionProvider {

    private static Set<String> addedReferences = new HashSet<>();

    @Override
    public CustomPropertyDefinition provideCustomSchemaDefinition(
        MemberScope scope, SchemaGenerationContext context) {
      if (scope.getAnnotationConsideringFieldAndGetter(Nullable.class) == null) {
        return null;
      }

      var schema = context.getGeneratorConfig().createObjectNode();
      var anyOfArrayNode = schema.putArray(context.getKeyword(SchemaKeyword.TAG_ANYOF));

      if (scope.getDeclaredType().isInterface()) {
        handleInterfaces(scope, anyOfArrayNode, context);
      } else {
        anyOfArrayNode.add(context.createDefinitionReference(scope.getType()));
      }

      anyOfArrayNode.add(new ObjectNode(JsonNodeFactory.instance).put("type", "null"));
      return new CustomPropertyDefinition(schema);
    }

    private static void handleInterfaces(
        MemberScope scope, ArrayNode arrayNode, SchemaGenerationContext context) {
      final var reflections = new Reflections(PACKAGE);

      var interfaceScope = String.format("%s:%s", scope.getDeclaringType(), scope.getMember());

      if (addedReferences.contains(interfaceScope)) {
        return;
      }

      addedReferences.add(interfaceScope);
      reflections
          .getSubTypesOf(scope.getDeclaredType().getErasedType())
          .forEach(
              subType -> {
                arrayNode.add(
                    context.createDefinitionReference(context.getTypeContext().resolve(subType)));
              });
    }
  }
}
```

**Comment by CarstenWickner** [comment]
Hi @catadincu,

I've introduced a new `Option.NULLABLE_ALWAYS_AS_ANYOF` that should cover your original requirement.
Once the release is out, you can give it a try.

**Comment by CarstenWickner** [comment]
Release [v4.37.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.37.0) has just been published containing the new `Option`.
