### ISSUE TITLE
Add support for `com.fasterxml.jackson.annotation.JacksonAnnotationsInside` annotation

### ISSUE THREAD

**Issue by smaarn** [victools/jsonschema-generator#486]
Jackson provides with this annotation which allows to indicate that an annotation actually contains jackson annotations. Allowing for "combo annotations".

Example: 

```
@JacksonAnnotationsInside
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@JsonTypeName
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  property = "__typename"
)
public @interface GraphQLJsonType {
}
```

The current jackson module doesn't account for this annotation when performing lookups for jackson annotations.

**Comment by CarstenWickner** [comment]
Release [v4.37.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.37.0) has just been published containing your merged PR with the support for `@JacksonAnnotaitonsInside`.
