### ISSUE TITLE
Support for custom examples

### ISSUE THREAD

**Issue by SimY4** [victools/jsonschema-generator#497]
For Swagger API annotated classes, it would be great to include provided examples as part of the schema.

IIUC, examples support is currently missing.

**Comment by CarstenWickner** [comment]
Hi @SimY4´,

Thanks for reaching out.
Support for including `examples` in a standard way is indeed missing -- on purpose.

This had been raised a few times in the past.
On #260 specifically, I described a way to set the examples based on the Swagger `@Schema(example = "...")` annotation.
In #360, an alternative approach was proposed by someone else.
My original opinion on this topic hasn't yet changed:
> The "examples" keyword is currently not part of the standard feature set. As one might want to consider the specific data type for which examples are being provided. So far, I didn't bother coming up with a proper implementation.
> I'm still hesitant to provide a generic implementation that only considers string example values and/or is based on a custom annotation.

Please have a look at those and consider adding this through configuration then.
