### ISSUE TITLE
Include enum descriptions in the generated schema

### ISSUE THREAD

**Issue by BroOfBros** [victools/jsonschema-generator#498]
Is it possible to include the `@JsonPropertyDescription` of enum values inside the generated schema?
```
public enum FieldType {
    @JsonPropertyDescription("""
            An auto-incrementing field of type integer.
            Usually used for IDs and unique fields.
            """
    )
    autoincrement,
    randomGuid,
    randomAlphanumeric;
}
```

Perhaps force the generator to use anyOf instead of enum?

**Comment by CarstenWickner** [comment]
Yes, via a custom definition provider, that can be done. I'm unfortunately short on time currently to write it for you now.
