### ISSUE TITLE
jsonschema-maven-plugin: Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by nimo23** [victools/jsonschema-generator#502]
I have something like this in my `pom.xml`:

```
<plugin>
    <groupId>com.github.victools</groupId>
    <artifactId>jsonschema-maven-plugin</artifactId>
    <version>${jsonschema.version}</version>
    <executions>
        <execution>
        <goals>
            <goal>generate</goal>
        </goals>
        </execution>
    </executions>
    <configuration>
        <schemaFilePath>src/main/resources/schemas</schemaFilePath>

        <!-- missing configuration property -->
        <deleteExistingFiles>true</deleteExistingFiles>
..
</plugin>
```

But I get an error from within the Eclipse pom.xml editor.

> Plugin execution not covered by lifecycle configuration: com.github.victools:jsonschema-maven-plugin:4.37.0:generate (execution: default, phase: compile)

I can bypass the error by using `<?m2e ignore?>` (see https://eclipse.dev/m2e/documentation/release-notes-17.html#new-syntax-for-specifying-lifecycle-mapping-metadata):

```
<plugin>
    <groupId>com.github.victools</groupId>
    <artifactId>jsonschema-maven-plugin</artifactId>
    <version>${jsonschema.version}</version>
    <executions>
        <execution>
         <!-- Required, otherwise I get an error -->
        <?m2e ignore?>
        <goals>
            <goal>generate</goal>
        </goals>
        </execution>
    </executions>
    <configuration>
        <schemaFilePath>src/main/resources/schemas</schemaFilePath>
..
</plugin>
```

After that, I can generate the schemas successfully. Maybe there is a better solution to this problem. I don't know if it's a Maven or a plugin issue.

Does anyone else encounter this issue?

**Comment by CarstenWickner** [comment]
Hi @nimo23,

This appears to be a known issue in Eclipse.
At least judging from this 13-year-old question on StackOverflow: https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

I'm afraid, this cannot be solved within the schema generator plugin itself. Glad to hear, you could get it to work.
