### ISSUE TITLE
Rename java class while generating schema?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#505]
Hi, is it possible to rename a class while generating the schema for it within the custom schema generators? 

eg I have a class called "BookModel" which I want to rename to just "Book" while generating the schema for it. (It would also be good for any definitions/references pointing to that model to use "Book" as well)

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

Sure thing, that is the purpose of the `SchemaDefinitionNamingStrategy` as described in the documentation here:
https://victools.github.io/jsonschema-generator/#names-in-global-quot-defs-quot-quot-definitions-quot

I've created an example showing it here: #506
