### ISSUE TITLE
More than one class example

### ISSUE THREAD

**Issue by coderextreme** [victools/jsonschema-generator#70]
I suggest you provide a several class example, especially for nested classes.

Thanks,

John

**Comment by CarstenWickner** [comment]
Hi John,

Don’t have much time right now.
But maybe have a look at the various unit/integration test.

**Comment by coderextreme** [comment]
https://www.web3d.org/specifications/java/X3DJSAIL.html is our API.   Root object is X3DObject.class.   JSON schema may be on the way to generating API for ECMAScript.   We have existing schema, both handgenerated and semiautomated from an object model written in XML.

I will clone the code now and get back to you on what I might need in addition.

So far generating JavaScript from Java is codebloated by an order of magnitude compared to similar APIs.  So were looking at going through JSON schema for "optimization."

John

**Comment by coderextreme** [comment]
We also have over 3000 JSON examples with which we can cross-compare the handwritten schema, the automated schema, and your potential generated schema to test your code.  I will work towards an example for headObjects and SceneObjects inside an X3DObject for the first phase.

I believe I have found the test cases you were talking about.

John

**Comment by coderextreme** [comment]
Ref examples:

https://github.com/victools/jsonschema-generator/blob/master/jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java

https://github.com/victools/jsonschema-generator/blob/master/jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorCustomDefinitionsTest.java

**Comment by coderextreme** [comment]
Oh, I have a pom.xml if you need one.

https://github.com/coderextreme/JavaSceneAuthoringInterfaceLibrary

You may extend that project, if desired.

Thanks!

John

**Comment by coderextreme** [comment]
note: build.sh in https://github.com/coderextreme/JavaSceneAuthoringInterfaceLibrary overrides your maven repository.  Do not run it, instead extract missing jars from it.

John

**Comment by coderextreme** [comment]
Okay, the generator starts falling apart on my scene object for the children of scene: Java snippets look like:

$ grep hildren SceneObject.java|egrep public"|"private
        private ArrayList<X3DNode> children = new ArrayList<>(); // MFNode acceptable node types: X3DChildNode|X3DMetadataObject|LayerSet or ProtoInstanceObject
        public ArrayList<X3DNode> getChildren()
        public SceneObject setChildren(ArrayList<X3DNode> newValue)
        public void addChildren(X3DNode newValue)
        public SceneObject addChildren(ProtoInstanceObject newValue)
        public void addChildren(X3DNode[] newValue)
        public void setChildren(X3DNode newValue)
        public SceneObject clearChildren()
        public boolean hasChildren()

**Comment by coderextreme** [comment]
python generated and handcrafted schemas appear here:

https://github.com/coderextreme/X3DJSONLD/tree/master/src/main/schema

**Comment by coderextreme** [comment]
Current test code (without learning much from examples, just trying to crank anything out):
```java
package net.coderextreme;

import org.web3d.x3d.jsail.Core.X3DObject;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfig;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaVersion;
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.Option;

public class SchemaG {
    public static void main(String [] args) {
        SchemaGeneratorConfig config = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON)
                .build();

        System.out.println((new SchemaGenerator(config).generateSchema(X3DObject.class)).toString());
    }
   }
```

**Comment by coderextreme** [comment]
schema generated by jsonschema-generator:
```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "StringBuilder": {
      "type": "object",
      "properties": {
        "coder": {
          "type": "integer"
        },
        "count": {
          "type": "integer"
        },
        "value": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "X3DConcreteElement": {
      "type": "object",
      "properties": {
        "parentObject": {
          "$ref": "#/$defs/X3DConcreteElement"
        },
        "validationResult": {
          "$ref": "#/$defs/StringBuilder"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "Scene": {
      "type": "object",
      "properties": {
        "children": {
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "parentObject": {
          "$ref": "#/$defs/X3DConcreteElement"
        },
        "validationResult": {
          "$ref": "#/$defs/StringBuilder"
        }
      }
    },
    "bufferedWriter": {
      "type": "object",
      "properties": {
        "cb": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "lock": {},
        "nChars": {
          "type": "integer"
        },
        "nextChar": {
          "type": "integer"
        },
        "out": {
          "type": "object",
          "properties": {
            "lock": {},
            "writeBuffer": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "writeBuffer": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "commentsList": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exificientGrammarX3D": {
      "type": "object"
    },
    "head": {
      "type": "object",
      "properties": {
        "commentsList": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "componentList": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "commentsList": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "level": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "parentObject": {
                "$ref": "#/$defs/X3DConcreteElement"
              },
              "validationResult": {
                "$ref": "#/$defs/StringBuilder"
              }
            }
          }
        },
        "metaList": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "commentsList": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "content": {
                "type": "string"
              },
              "dir": {
                "type": "string"
              },
              "http_equiv": {
                "type": "string"
              },
              "lang": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "parentObject": {
                "$ref": "#/$defs/X3DConcreteElement"
              },
              "scheme": {
                "type": "string"
              },
              "validationResult": {
                "$ref": "#/$defs/StringBuilder"
              }
            }
          }
        },
        "parentObject": {
          "$ref": "#/$defs/X3DConcreteElement"
        },
        "unitList": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "category": {
                "type": "string"
              },
              "commentsList": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "conversionFactor": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "parentObject": {
                "$ref": "#/$defs/X3DConcreteElement"
              },
              "validationResult": {
                "$ref": "#/$defs/StringBuilder"
              }
            }
          }
        },
        "validationResult": {
          "$ref": "#/$defs/StringBuilder"
        }
      }
    },
    "includeSubdirectoryPaths": {
      "type": "boolean"
    },
    "parentObject": {
      "$ref": "#/$defs/X3DConcreteElement"
    },
    "profile": {
      "type": "string"
    },
    "validationResult": {
      "$ref": "#/$defs/StringBuilder"
    },
    "version": {
      "type": "string"
    }
  }
}
```

**Comment by coderextreme** [comment]
I know there's a lot of differences with our schema and yours. I think some of these issues can be conquered with annotations on the Java.  We generate our Java code from XML using XSLT so creating JAX-B bindings may be feasible, and probably should be researched.

**Comment by coderextreme** [comment]
script code for building Java code and running it:
```sh
#!/bin/bash

# generate a schema from X3DJSAIL

export HOME=c:/Users/coderextreme
export REPOSITORY=${HOME}/.m2/repository
javac -cp "${REPOSITORY}/org/slf4j/slf4j-jdk14/1.7.12/slf4j-jdk14-1.7.12.jar;${REPOSITORY}/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar;${REPOSITORY}/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar;${HOME}/jsonschema-generator/jsonschema-generator/target/jsonschema-generator-4.10.0-SNAPSHOT.jar;../jars/X3DJSAIL.3.3.full.jar;." net/coderextreme/SchemaG.java
npm install -g jsonlint
java -cp "${REPOSITORY}/org/slf4j/slf4j-jdk14/1.7.12/slf4j-jdk14-1.7.12.jar;${REPOSITORY}/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar;${REPOSITORY}/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar;${HOME}/jsonschema-generator/jsonschema-generator/target/jsonschema-generator-4.10.0-SNAPSHOT.jar;../jars/X3DJSAIL.3.3.full.jar;." net.coderextreme.SchemaG | jsonlint
```

**Comment by coderextreme** [comment]
Not sure if it will help, but here's our one version back JSON schema generator (from XML description):  https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/python/etgenerateJSONschema.py

**Comment by CarstenWickner** [comment]
Hi @coderextreme,

I'm afraid I don't have the spare time to look into this in such a general way for you.
From a brief look I did take into the linked repository and schema example:
- There is some heavy use of tuples (i.e. arrays with specific kinds of values at specific indexes), which will need to be handled through "Custom Definition" at least to define those tuples – the parts (i.e. for a single index in the tuple/array) you might be able to fall-back on auto-generated schemas parts then.
- The main challenge you will have in automatically generating schemas from your codebase is the high degree of hard-coded knowledge within the method bodies.
  - There is no nice way of getting it out of there and into a schema.
  - If you were to externalize a lot of these things into JAXB annotations (and/or custom annotations of your own), you might get there – but I don't foresee an enjoyable ride there.
  - I suspect you'd need a considerable amount of refactoring or you'd have to duplicate all that knowledge in the configuration on the schema generator (which is possible but I personally wouldn't recommend that since it'd practically be what you have already).

I'm happy to help out if you have specific questions regarding how to configure certain things, but the refactoring of your codebase dramatically exceeds what I have time for.

**Comment by CarstenWickner** [comment]
Since there hasn’t been any activity for a while, I‘ll close this here.

As per my previous comment I‘m happy to help with more specific questions.
