### ISSUE TITLE
Object class not defined when specified as part of a Map.

### ISSUE THREAD

**Issue by shnako** [victools/jsonschema-generator#71]
I'm trying to generate a schema based on the following class:

```java
package mypackage;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Response {
    @JsonProperty("collection")
    Collection collection;

    @JsonProperty("results")
    Map<String, Result> results;

    @JsonProperty("total_hits")
    int totalHits;
}
```

using the following configuration:
```java
SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(new ObjectMapper(), OptionPreset.PLAIN_JSON);
SchemaGeneratorConfig config = configBuilder
        .with(Option.DEFINITIONS_FOR_ALL_OBJECTS)
        .build();
SchemaGenerator generator = new SchemaGenerator(config);
```

and the result is:
```json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "definitions" : {
    "Collection" : {
      "type" : "string",
      "enum" : [ "A", "B" ]
    },
    "Map(String,Result)" : {
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "collection" : {
      "$ref" : "#/definitions/Collection"
    },
    "results" : {
      "$ref" : "#/definitions/Map(String,Result)"
    },
    "totalHits" : {
      "type" : "integer"
    }
  }
}
```

As you can see, the `Result` object (which contains 2 strings) is not being detailed even though I specified `DEFINITIONS_FOR_ALL_OBJECTS`. I've tried specifying a `Result` variable in the `Response` class and that generates a `Result` definition but it's still not mapped into the definition for `Map(String,Result)`.

**Comment by CarstenWickner** [comment]
Hi @shnako,

By default, `Map`s are not handled automatically. But you can easily enable it by adding something like this:
```java
configBuilder.forTypesInGeneral()
        .withAdditionalPropertiesResolver(scope -> {
            if (scope.getType().isInstanceOf(Map.class)) {
                return scope.getTypeParameterFor(Map.class, 1);
            }
            return null;
        });
```
That should do the trick.

**Comment by shnako** [comment]
That worked perfectly, thank you very much!
Is this explicitly detailed somewhere in the docs (e.g. for maps, do this)? If not, I think it should be, just to avoid other asking the same question as me and wasting your time.
Might also be worth having it as a simple Option flag since it's such a common use case.

Again, thank you for maintaining this awesome project so well!

**Comment by CarstenWickner** [comment]
@shnako it is mentioned in the main `jsonschema-generator` [README](https://github.com/victools/jsonschema-generator/tree/master/jsonschema-generator#example-dynamically-setting-the-additionalproperties-attribute) – but not as "for `Map`s do this ...", which sounds very reasonable to be added to the wiki/documentation. Thanks for the hint and kind words.

**Comment by CarstenWickner** [comment]
I added an "FAQ" section to the documentation now, describing this as well: https://github.com/victools/jsonschema-generator/wiki#how-to-represent-a-mapk-v-in-a-generated-schema
