### ISSUE TITLE
Maven plugin - Configuration of the generator

### ISSUE THREAD

**Issue by JanLabrie** [victools/jsonschema-generator#79]
The configuration of a Generator in the pom.xml should support :
- Base definition: One of the labels of OptionPreset. PLAIN_JSON as the default value.
- Options that have to be enabled
- Options that have to be disabled

**Comment by JanLabrie** [comment]
Proposal:
```xml
<options>
    <preset>FULL_DOCUMENTATION</preset>
    <enabled>
        <option>DEFINITIONS_FOR_ALL_OBJECTS</option>
        <option>FORBIDDEN_ADDITIONAL_PROPERTIES_BY_DEFAULT</option>
    </enabled>
    <disabled>
        <option>SIMPLIFIED_ENUMS</option>
    </disabled>
</options>
```

What do you think Carsten?

**Comment by CarstenWickner** [comment]
I like it.

**Comment by JanLabrie** [comment]
PR merged. Issue can be closed.
