### ISSUE TITLE
Maven plugin - Do we want to support a default configuration?

### ISSUE THREAD

**Issue by JanLabrie** [victools/jsonschema-generator#82]
Currently the Maven plugin has a default configuration which consist of all known Modules from the jsonschema-generator project.

When this configuration is usefull to a large part of the user group we should keep it. Else we should remove it, because it would require all Modules to be on the Maven dependency list.

@Carsten: I believe you are in favor of removing the default configuration right?

**Comment by CarstenWickner** [comment]
Yes, I'd prefer not to include any modules by default.
- That would still result in a schema with the proper structure being generated.
- When specific configurations are being added, it will not result in the confusing situation of some (default) configuration details to disappear.
- The only meaningful default configuration in my view is the `OptionPreset.PLAIN_JSON`.

**Comment by JanLabrie** [comment]
OK. I will remove it.

**Comment by JanLabrie** [comment]
PR merged. Issue can be closed.
