### ISSUE TITLE
@JsonNaming Annotation Ignored

### ISSUE THREAD

**Issue by shnako** [victools/jsonschema-generator#89]
I have a class like this:

```java
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class MyObject {
    private String s3Path;
}
```

Because of the JsonNaming annotation, the field will be returned as s3_path but the generated schema will generate it as s3Path so when receiving the object on the other end it fails because it expects s3Path but receives s3_path in the JSON payload.

It would be great if this annotation could be supported and the naming adjusted as specified by the case to avoid mismatches.

**Comment by CarstenWickner** [comment]
Hi Vlad,

I’m confident this can already be achieved through the `PropertyNameOverride` configuration.

Could you maybe configure it yourself and then share your working code? That would give me a meaningful place to start from.

Happy to add the support for that.
I‘d also appreciate pointers to the respective documentation explaining what strategies there are and how they behave exactly.

**Comment by shnako** [comment]
Hi @CarstenWickner,

Thanks for the super quick reply. 

You were right, that did work nicely. Here's the extra configuration I had to add:
```
        configBuilder.forFields().withPropertyNameOverrideResolver(field ->
                CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, field.getName()));
```

This uses the [CaseFormat from Guava](https://guava.dev/releases/22.0/api/docs/com/google/common/base/CaseFormat.html).

Here's the documentation for [PropertyNamingStrategy](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/PropertyNamingStrategy.html) - it details the different options quite well.

Thanks again for doing such a great job maintaining this really useful project.

If there's anything I can help with please let me know.

**Comment by CarstenWickner** [comment]
Hi @shnako,

In order to avoid the extra dependency to Guava, I have to stick to the annotated `PropertyNamingStrategy`. Implemented this now in GH-100.

With the next v4.12.0 release `@JsonNaming` annotations should be considered out-of-the-box then.

**Comment by shnako** [comment]
Works great! Thank you very much for this.
