### ISSUE TITLE
Ordering and grouping of imports

### ISSUE THREAD

**Issue by JanLabrie** [victools/jsonschema-generator#96]
Carsten,

About the ordering and grouping of the imports. Can we define the rule for this?
I think best thing to do is to add this to the checkstyle.xml.

[ImportOrder Rule](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.html)

Jan

**Comment by CarstenWickner** [comment]
I gave this a try but couldn't manage to prevent empty lines between imports.

This would probably be a good opportunity to move all individual checkstyle configuration files up into the parent directory to ensure that they are kept in sync.

**Comment by CarstenWickner** [comment]
@JanLabrie apparently the `checkstyle` plugin dependency was too old. The line separators weren't checked in the older version – the newer version properly enforces the fact that no separators are expected between imports.
